### ISSUE TITLE
MultipleApiVersions is not called

### ISSUE THREAD

**Issue by SashaBezugliy** [domaindrivendev/Swashbuckle#1057]
Hi,
I want to force to include both methods in a Swagger document. The second method is simply skipped in `MultipleApiVersions` because both methods have the same route. Once i change a Route for any action, `MultipleApiVersions` is called for both. 

        [MapToApiVersion("6.0")]
        [Route("items")]
       public  Task<Item> PostItemsAsync([FromBody] Item item)
        {
        }
        [MapToApiVersion("8.0")]
        [Route("items")]
        [HttpPost]
        public Task<ItemV8> PostItemAsyncV8([FromBody] ItemV8 item)
        {
        }

Thanks

**Comment by VisualBean** [comment]
Effectively the same as #1060

**Comment by commonsensesoftware** [comment]
@SashaBezugliy it looks like you're using ASP.NET API Versioning. Did you know that there is an [API Explorer for API Versioning](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Versioning.ApiExplorer) to support this now?  You can see the Web API sample [here](https://github.com/Microsoft/aspnet-api-versioning/tree/master/samples/webapi/SwaggerWebApiSample). Although it's RC, it's stable. I'm tightening up the last few bits this week and I think things will be ready for the first, official release.

Your problem is addressed by the **IApiExplorer** implementation for API versioning that will bucketize actions by API version. There's very little you need to do in Swashbuckle to light it up. Feel free to ask specific questions related Swashbuckle and API Versioning on that [repo](https://github.com/Microsoft/aspnet-api-versioning/issues).

**Comment by SashaBezugliy** [comment]
Hi @commonsensesoftware ,
Can you point out what should be done in Swashbuckle to light it up?

**Comment by commonsensesoftware** [comment]
In addition to the API versioning and Swashbuckle packages, you also need the [ASP.NET Web API Versioned API Explorer](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Versioning.ApiExplorer) package. Then you need to call `configuration.AddVersionedApiExplorer()` in your application setup. Finally, you need to use the API explorer to call **MultipleApiVersions** in the Swagger configuration. A complete example of what this might look like can be found [here](https://github.com/Microsoft/aspnet-api-versioning/blob/master/samples/webapi/SwaggerWebApiSample/Startup.cs). Your application configuration may be slightly different.

**Comment by SashaBezugliy** [comment]
@commonsensesoftware thank you very much! That was exactly what i needed.
