### ISSUE TITLE
Unable to get oauth2 to work

### ISSUE THREAD

**Issue by noamarbel** [domaindrivendev/Swashbuckle#106]
Hello,

I have been trying to get oauth2 to work for the last few days with no success. Whatever I do, I do not get the UI element to let me authenticate (the one that has the .api-ic class associated with it). I set up the Authorization like described, I enabled oauth2 on the UI Config. All looks good, yet the selection of an element with the .api-ic class returns no elements on the UI. 

Do I need to set any attributes on my API to make it work?

Any help as to what I am doing wrong, or what needs to be done will be greatly appreciated.

**Comment by omniscient** [comment]
I downloaded latest and looked at your sample and I don't understand. None of your controllers actually validate security in Dummy.Core. When I use the Dummy.WebHost project to tests methods on all the controllers, no oauth headers gets added.

Start your webhost project, open fiddler, Composer tab and paste that in:

GET http://localhost:3429/ConflictingActions HTTP/1.1
Referer: http://localhost:3429/swagger/ui/index#!/ConflictingActions/ConflictingActions_GetAll
Accept: application/json
Accept-Language: en-US,en;q=0.8,fr-CA;q=0.5,fr;q=0.3
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Connection: Keep-Alive
DNT: 1
Host: localhost:3429

You get Not implemented. No security check whatsoever.

**Comment by omniscient** [comment]
I found another report from today. Another Dev has a related problem with OAuth in https://github.com/domaindrivendev/Swashbuckle/issues/267. NVM my comment here and let's figure this out as part of 267.

**Comment by danutzplusplus** [comment]
I don't think it's Swagger/Swashbuckle's job to perform security checks. It just wraps your service, performs OAuth calls to the identity provider and then calls to your service with the acquired tokens. And offers you UI for all this. The service itself will need to be protected by something else that interacts with your identity provider in order to check the validity of the issued token.

**Comment by omniscient** [comment]
@danutzplusplus My point is: The @domaindrivendev  says "Go check my sample". I opened the sample and it is incomplete. It doesn't go grab any token. The Get request I posted is one directly taken from the sample, (latest code as of yesterday) after clicking on the "test" button to generate a test request. According @domaindrivendev , everything is supposed to be hooked in the sample app but as you can see, there is no token on the request therefore I cannot easily replicate the sample as he said on Oct 23, 2014 in this thread because it doesn't work. It might be just me, but it is not obvious.

I am really appreciative of the work and thank all members who worked on swashbuckle, it is truly a very important piece of software that can save headaches but getting the impression from the main doc that something is baked in only to find out that it requires some effort to implement is not good in terms of evaluating work vs. actually doing the work.

**Comment by domaindrivendev** [comment]
The sample app is there to test and demonstrate a range of different SB features. Each controller is testing a specific one which I've tried to make obvious by the name. You should look at the "ProtectedResourcesController" because that's the one for specifically testing security schemes.

Agreed, docs could be more thorough on this subject but frankly there are only so many hours in the day, there are other higher priority features and I do have a day job too. Rather than complaining you should put together a pull request that improves the documentation - that would be more in the spirit of open source software.

**Comment by omniscient** [comment]
That's all I needed @domaindrivendev. I am new to this project. By reading this thread and the available material, I didn't see that only ProtectedResourcesController had the security stuff implemented.

I'll create a pull request to help others, that's a given. I just needed help to get started...

**Comment by domaindrivendev** [comment]
No worries - glad you got it figured out

**Comment by Marusyk** [comment]
Can I enable oauth2 and then set client_id and client_secret by User from UI (authorization window)?
