### ISSUE TITLE
Adding Authorization header

### ISSUE THREAD

**Issue by dtmatthews** [domaindrivendev/Swashbuckle#1171]
I have an HMAC secured WebApi and I cannot get the Swagger UI passing the client generated hash in the Authorization header.

I've added custom js to generate my hash but when I add it to the authorizations collection it doesnt work.

If I add it to the headers collection directly it gets passed in the request message but in the headers not in the Authorization header specifically.

I'm sure I'm making a stupid mistake but can someone offer an example of a hashed Authorization setup as required for my hmac security?

thanks

**Comment by dtmatthews** [comment]
For the time being I've hijacked the operation level Authorization UI that swashbuckle generates and just insert my hmac in to that but I would like to know the right way to add the Authorization header programmatically rather than my current approach because these values arent operation-specific.

**Comment by domaindrivendev** [comment]
There's no native support in Swagger or Swashbuckle for this type of authentication. However, there's many ways to extend both frameworks to meet your needs and the best place for inspiration would be Stackoverflow rather than this project's issue list.

I just did a quick Google and found the following blog which I imagine could be very helpful. If you haven't done so already, you should check it out:

https://www.darraghoriordan.com/2017/01/11/swagger-ui-custom-hmac-hash-authentication/
