### ISSUE TITLE
API Endpoints list empty: no paths

### ISSUE THREAD

**Issue by dydFreeman** [domaindrivendev/Swashbuckle#1243]
**Problem:** Swagger runs fine in my .NET WebAPI project, but no API endpoint is listed.

This is what i get from: http://localhost:62536/swagger/docs/v1

    {
       "swagger":"2.0",
       "info":{
          "version":"v1",
          "title":"Backend.WebApi"
       },
       "host":"localhost:62536",
       "schemes":[
          "http"
       ],
       "paths":{
    
       },
       "definitions":{
    
       }
    }

**webApiConfig.cs**

```
public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services
            AutoMapperConfiguration.Configure();           
            ConfigureIoC(config);

            // Web API routes
            config.MapHttpAttributeRoutes();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional    }
            );

            var jsonFormatter = config.Formatters.OfType<JsonMediaTypeFormatter>().First();
            jsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();


            // SwaggerConfig.Register();
        }
```

**swaggerConfig.cs**   

 

    using System.Web.Http;
    using WebActivatorEx;
    using Backend.WebApi;
    using Swashbuckle.Application;
    
    [assembly: PreApplicationStartMethod(typeof(SwaggerConfig), "Register")]
    
    namespace Backend.WebApi
    {
        public class SwaggerConfig
        {
            public static void Register()
            {
                var thisAssembly = typeof(SwaggerConfig).Assembly;
    
                GlobalConfiguration.Configuration
                    .EnableSwagger(c =>
                        {
          
                    
                            c.SingleApiVersion("v1", "Backend.WebApi");
    
                        })
                    .EnableSwaggerUi(c =>
                    
                        });
            }
        }
    }
Here's a controller example: 

**testController.cs**

     namespace Backend.WebApi.Controllers
        {

    
        [Authorize]
        [RoutePrefix("api/test")]
        public class TestController : ApiController
        {
            private readonly IAppService _appService;
    
            public TestController(IAppService appService)
            {
                _appService = appService;
            }
    
            [Route("vehicles/all")]
            public List<VehicleViewModel> GetVehicles()
            {
                return _appService.GetVehicles();
            }
    [...]

I tried enabling XML comment too (since my app has some of them), but nothing pops up on the list.
Am i missing something?
Thanks.

**Comment by dydFreeman** [comment]
Moving the config part from SwaggerConfig.cs to WebApiConfig.cs fixed the issue.

**webApiConfig.cs**

```
public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
[...]
            config
            .EnableSwagger(c => c.SingleApiVersion("v1", "Backend.WebApi"))
            .EnableSwaggerUi();
```

**Comment by 501st-alpha1** [comment]
I ran into this same issue, and your solution also worked for me (thanks!).

I did some more troubleshooting to narrow down the problem, and I found that the problem occurs when calling `EnableSwagger` on the `GlobalConfiguration.Configuration` global object, rather than the specific `HttpConfiguration` in `WebApiConfig`.

As an alternative fix, I changed the `Register` method header:

```
public static void Register(HttpConfiguration config)
```

and updated the `EnableSwagger` line:

```
config.EnableSwagger(c => ...
```

and called that method directly from `WebApiConfig.Register`:

```
SwaggerConfig.Register(config);
```

and it worked.  (This also requires removing the `PreApplicationStartMethod` attribute in `SwaggerConfig.cs`.)

(I also tried only removing the `PreApplicationStartMethod` attribute, and leaving the `GlobalConfiguration.Configuration` line alone, since [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.web.preapplicationstartmethodattribute?view=netframework-4.8) mention:

> There is no guarantee of the order in which the assembly-defined application start methods are called. As a result, each registered start method should be coded to run in isolation and should not depend on side effects from other registered start methods.

but the original issue still occurred, so the `GlobalConfiguration` line is (part of) the problem.)

I'd open a PR against [`SwaggerConfig.cs.pp`](https://github.com/domaindrivendev/Swashbuckle.WebApi/blob/master/Swashbuckle.WebHost/Nuget/Content/App_Start/SwaggerConfig.cs.pp), but I'm not sure if it's possible for a NuGet package to automatically adjust `WebApiConfig.cs`, or if there's a better way to fix this problem.

@dydFreeman since it seems to be a problem with the code added by this package, would you consider reopening this issue?  (I realize that the project's maintainer has mostly moved on, but this does still seem to be a valid issue, even if it does have a workaround.)

**Comment by 3UR** [comment]
> I ran into this same issue, and your solution also worked for me (thanks!).
> 
> I did some more troubleshooting to narrow down the problem, and I found that the problem occurs when calling `EnableSwagger` on the `GlobalConfiguration.Configuration` global object, rather than the specific `HttpConfiguration` in `WebApiConfig`.
> 
> As an alternative fix, I changed the `Register` method header:
> 
> ```
> public static void Register(HttpConfiguration config)
> ```
> 
> and updated the `EnableSwagger` line:
> 
> ```
> config.EnableSwagger(c => ...
> ```
> 
> and called that method directly from `WebApiConfig.Register`:
> 
> ```
> SwaggerConfig.Register(config);
> ```
> 
> and it worked. (This also requires removing the `PreApplicationStartMethod` attribute in `SwaggerConfig.cs`.)
> 
> (I also tried only removing the `PreApplicationStartMethod` attribute, and leaving the `GlobalConfiguration.Configuration` line alone, since [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.web.preapplicationstartmethodattribute?view=netframework-4.8) mention:
> 
> > There is no guarantee of the order in which the assembly-defined application start methods are called. As a result, each registered start method should be coded to run in isolation and should not depend on side effects from other registered start methods.
> 
> but the original issue still occurred, so the `GlobalConfiguration` line is (part of) the problem.)
> 
> I'd open a PR against [`SwaggerConfig.cs.pp`](https://github.com/domaindrivendev/Swashbuckle.WebApi/blob/master/Swashbuckle.WebHost/Nuget/Content/App_Start/SwaggerConfig.cs.pp), but I'm not sure if it's possible for a NuGet package to automatically adjust `WebApiConfig.cs`, or if there's a better way to fix this problem.
> 
> @dydFreeman since it seems to be a problem with the code added by this package, would you consider reopening this issue? (I realize that the project's maintainer has mostly moved on, but this does still seem to be a valid issue, even if it does have a workaround.)

+1 had the same issue this fixed it.
