### ISSUE TITLE
Support for XML comment "see"

### ISSUE THREAD

**Issue by cosmo0** [domaindrivendev/Swashbuckle#136]
I'm using XML comments for my controllers. If I add a `<see cref="class" />` in my comment, it results in missing words.

````csharp
/// <summary>
/// Cancels an <see cref="Order" />
/// </summary>
/// <param name="id">The order ID</param>
[DELETE("api/v1/orders/by_id/{id}")]
public void CancelOrder(int id, string reason) { }
````

The description in Swagger will be "Cancels an".

Using a code documentation generation tool like SandCastle or Doxygen results in displaying the "Order" word, with a link to the specified class. I expected Swashbuckle to at least display "Order".

**Comment by domaindrivendev** [comment]
I'd question the value of generating C# "style" documentation for WebApi controller actions? Outside of their own unit tests, they're rarely (if ever) going to be invoked by a developer. They're typically invoked by the framework itself. So, who would be the intended audience of such documentation???

Consumers of your application are not interested in C# style documentation because that's not how they will use it. HTTP/REST style documentation, as provided by Swashbuckle/Swagger, seems far more appropriate.

I'm going to close this issue as it's low on the list of priorities and as of now I'm failing to see the value. If it comes up again we can revisit.

**Comment by cosmo0** [comment]
It's not so much a matter of utility as a matter of habit and company policies (StyleCop rules for instance).

If you point me to the part of the code that parses the methods comments, I can make a PR.

**Comment by domaindrivendev** [comment]
Discussion on using inline code comments for swagger properties used by non-human consumers (e.g. swagger-codegen)  #164
