### ISSUE TITLE
Generate endpoint description from controller summary header

### ISSUE THREAD

**Issue by emardini** [domaindrivendev/Swashbuckle#146]
It seems that the generator does not "see" the controller header when generating the api doc, so the Description field is not being generated, I have this result:

{
   "swaggerVersion":"1.2",
   "apis":[
      {
         "path":"/Consumers"
      },
      {
         "path":"/Memberships"
      },
      {
         "path":"/Places"
      },
      {
         "path":"/Products"
      }
   ],
   "apiVersion":"1.0.0.0",
   "info":{
      "title":"Api",
      "description":"API",
      "contact":"someemail@some.comi"
   }
}

Is it possible to generate the description from the controller header? 
Something like this:

{
   "swaggerVersion":"1.2",
   "apis":[
      {
         "path":"/Consumers",
        "description":"some description"
      }
   ],
   "apiVersion":"1.0.0.0",
   "info":{
      "title":"Api",
      "description":"API",
      "contact":"someemail@some.comi"
   }
}

Thank you

**Comment by tillig** [comment]
It appears there's no current support for such a thing but the addition of an `IResourceFilter` in the same way there's `IOperationFilter` and `IModelFilter` could enable it.

**Comment by domaindrivendev** [comment]
Actually, the upcoming version of Swashbuckle (currently available as an alpha release) does introduce a new extensibility interface - IDocumentFilter, for making tweaks to the entire document.

With that said though, it also transitions to Swagger 2.0 which is very different to the the format outlined above. In fact, with the new format, you may be able to do this with an IOperationFilter because the top-level grouping is achieved with a "tag" approach, whereby each operation is assigned a tag for grouping. These tags can also include a description which you could pull from the controller metadata in an IOperationFilter.

You should try it out if you get a chance:

Install-Package Swashbuckle -Pre

And the docs - https://github.com/domaindrivendev/Swashbuckle/tree/swagger_2.0

Going to close the issue as the above should be possible with the pre-release package and I'm making a big push toward Swagger 2.0, limiting support for the 4.X versions which are bound to Swagger 1.2
