### ISSUE TITLE
Not discovering XML response codes

### ISSUE THREAD

**Issue by jchadwick** [domaindrivendev/Swashbuckle#152]
Using new 5.0 bits I've lost the response codes declared as xml doc comments with the following syntax in 4.x:
/// &lt;response code="400">Invalid Resource Id&lt;/response>

**Comment by benpriebe** [comment]
+1

**Comment by domaindrivendev** [comment]
I'm on the fence about how best to support this in the new Swagger 2.0 world.

Firstly, it's never been my favorite feature because it relies on code comments for parts of the spec that will ultimately affect functionality across the swagger ecosystem. For example, the code generated for a client (see swagger-codegen) will be affected by the described response codes.

When it's just descriptive fields, this is less of a concern, hence I've no issue using the standard XML tags for documentation. But for response codes it seems a little less satisfactory to rely on comments that easily (and inevitably do) become out of sync with the actual implementation.

On the other hand, I can see how this feature would be useful to get de documentation up and running for your service quickly.

**Comment by domaindrivendev** [comment]
Re-introduced this functionality into the swagger_2.0 branch.

**Comment by domaindrivendev** [comment]
Discussion on using inline code comments for swagger properties used by non-human consumers (e.g. swagger-codegen)  #164
