### ISSUE TITLE
Support for application pool "classic mode"?

### ISSUE THREAD

**Issue by vukoje** [domaindrivendev/Swashbuckle#156]
Can Swashbuckle run on web applications which app pools has Manager pipeline mode: Classic?

When I am in classic mode I get an error:
HTTP Error 500.21 - Internal Server Error
Handler "SwashbuckleUiHandler" has a bad module "ManagedPipelineHandler" in its module list.

**Comment by domaindrivendev** [comment]
To serve the swagger-ui using only the WebApi pipeline, the SB handlers need to be called for URL's with extensions (.html, .js, .css etc.). IIS disables this by default and handles these requests with a static file handler, bypassing the WebApi pipeline. So - SB needs to opt out of this behavior for the swagger-ui requests. It has gone through several different approaches in doing this and from your issue it looks like the current approach breaks in classic mode:

  <system.webServer>
    <handlers>
      <add name="SwaggerUiHandler" verb="*" path="swagger/ui/*" type="Swashbuckle.Application.SwaggerUiHandler, Swashbuckle.Core" preCondition="managedHandler" />
    </handlers>
  </system.webServer>

Can you try removing the handler mapping above and reverting to the old approach which is probably more likely to work but can have a slight impact performance if your website serves a lot of static files.

**Comment by vukoje** [comment]
Thanks for clarification, I now get the whole picture.
You proposal would probably work but for big site with high load (my case) this performance hit is not something I can afford. Tnx again.

**Comment by domaindrivendev** [comment]
This is really useful feedback because I definitely don't want to limit the application of SB to sites that don't have a high load. Actually, the use of RUMMFAR and it's relative impact to overall performance is something I've been discussing a lot recently. I've also been lucky enough to get some input from the WebApi team at MS.

The general consensus is that the performance impact is likely to be negligible unless your site serves a high number of static files, i.e. where there is no need to invoke any managed code and in particular the URL Routing module.

For example, if your website is just an "API" then all requests would be served by managed code anyway and hence enabling or not enabling RUMMFAR becomes a mute point. If your website hosts UI alongside an API, then what percentage of requests would be eligible to skip managed code? If your using MVC, then most if not all html will typically be served up via managed code anyway. That just leaves .js, .css and images - usually downloaded once and then cached in browsers.

I'm not necessarily saying I'm all for RUMMFAR but I just want to play devils advocate and see if I can distill the myth from the reality on this topic. If you have any feedback or personal experience to share it would be very helpful.

Finally, there is a potential workaround whereby I proxy every asset in the [swagger-ui](https://github.com/swagger-api/swagger-ui) via extension-less URL equivalents. However this would be a maintenance nightmare, particularly for keeping in sync with the swagger-ui, and I'd like to avoid this approach if possible.

Thanks

**Comment by domaindrivendev** [comment]
I've just released Swashbuckle 5.0.0. This release avoids the whole RAMMFAR debacle by proxying all of the UI assets through extension-less URL's. This should hopefully resolve your issue. Can you try it out when you get a chance.

Thanks

**Comment by vukoje** [comment]
Works like a charm! Thank you!
