### ISSUE TITLE
How to generate custom schema with example?

### ISSUE THREAD

**Issue by pareshnawale** [domaindrivendev/Swashbuckle#162]
Hi 

As per Swagger 2.0 specification schema object now includes example. Could you please explain how to achieve that using Swashbuckle?

Thanks,
Paresh

**Comment by domaindrivendev** [comment]
You can set the example property on a schema object by wiring up an "ISchemaFilter" as shown below:

__AddSchemaExamples.cs__

    public class AddSchemaExamples : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
        {
            if (type == typeof(Product))
            {
                schema.example = new Product
                    {
                        Id = 123,
                        Type = ProductType.Book,
                        Description = "Treasure Island",
                        UnitPrice = 10.0M
                    };
            }
        }
    }

__SwaggerConfig.cs__

    httpConfig 
        .EnableSwagger(c =>
             {
                 c.SchemaFilter<AddSchemaExamples>()
             });

__NOTE__: while this WILL be emitted in the Swagger JSON it will NOT show up any differently in the UI. Unfortunately, swagger-ui is well behind the 2.0 spec and playing catch up to support a lot of the new spec items:

https://github.com/swagger-api/swagger-ui/issues/618

**Comment by pareshnawale** [comment]
Thank you for your reply. It makes sense now why I wasn't able to see it in Swagger UI

**Comment by gzinger** [comment]
Is there currently any workaround for this to work all the way?

**Comment by domaindrivendev** [comment]
Instead of setting "schema.example" could you try setting "schema.default" in your schema filter?

I think (unexpectedly IMO) this is the property that the swagger-ui uses to pre-populate the "Model Schema" in the swagger-ui.

Let me know if this works - thx

**Comment by gzinger** [comment]
Actually, even setting schema.example worked for SOME of the types but not for the others. And after I updated the Swashbuckle to the latest version they even showed up in the UI. However, I couldn't get other types set in schema.example to show up no matter what I did. And I don't see ANY difference in terms of definitions between the types that show up and the ones that don't show up. Changing code so that it sets schema.@default instead of schema.example worked for ALL the types that I defined, but I am wondering if this is the right approach and what is the difference between schema.example and schema.@default ?

Thanks.

**Comment by gzinger** [comment]
Also, is there any way to specify a sample for collection (array) of objects? In HelpPageConfig I used to be able to specify it as IEnumerable<MyType> and provide an example that would return a few of MyTypes like so:
{code}
...
typeof(IEnumerable<AccountWarningModel>), GetSampleAccWarnings()
...

public static AccountWarningModel[] GetSampleAccWarnings() {
			return new AccountWarningModel[]
			{
				GetSampleAccWarning(123), GetSampleAccWarning(345)
			};
		}

{code}

Here it always return a single object from the collection. How can I tell it to look at the collections as well?

**Comment by gzinger** [comment]
It's been almost a year since I posted my last question I am still looking for an answer. Is there any way to specify a sample for collection (array) of objects? Please tell how?

**Comment by Jeevi21** [comment]
Is there any way to achieve this without using swashbuckle? Just using swagger core?

**Comment by danandrei-pascu** [comment]
Hi @domaindrivendev ,
Regarding @gzinger question, any chance to have an answer for that issue?
I'm experiencing the same problem, and I'm not able to specify a sample for collection (array) of objects. I'm using version 5.4.0.

Even if I'm able to assign a list of objects to schema.example, the output is not the expected one, since it will begin with '[[' and it will end with ']]' (instead of '[' ... ']').

Thanks!
