### ISSUE TITLE
Different API Docs and API Base Paths

### ISSUE THREAD

**Issue by fini-eng01** [domaindrivendev/Swashbuckle#163]
Right now, it appears that the location of the api docs is always derived from the api base path.

![image](https://cloud.githubusercontent.com/assets/10520480/5727533/b8ddacaa-9b18-11e4-8445-4fe9617dfed4.png)

We have a deployment scenario where we would like the apidocs url to be different (we want the api docs in a different subdomain) from the api base path but the ability to configure for this scenario does not appear to be available.

Is there a way to configure this that we are not aware of? If not, is this something that can be added?

As a workaround, we added our desired path to the GetDiscoveryUrls method of SwaggerUIHandler.cs in the manner below.

![image](https://cloud.githubusercontent.com/assets/10520480/5729354/a4818750-9b26-11e4-9caf-f0bd4d85d12f.png)

This results in the following javascript in the index.html page.

![image](https://cloud.githubusercontent.com/assets/10520480/5729447/5e44ace4-9b27-11e4-9700-3d4b323bd67e.png)

Note that our base api path is: https://sandboxb.somedomain.com/somedir

Thanks

**Comment by domaindrivendev** [comment]
I'm a little confused by this setup ... will you have two separate deployments of your service at each subdomain?

**Comment by fini-eng01** [comment]
We have a single deployment of the service (the subdomains are just different bindings to the same website). 

What we'd like is for the swagger UI to be in one subdomain and the api itself in another, for (a more functional) example: The swagger UI would be accessed by developers at  developers.somedomain.com/somedir while the API itself is accessed through api.somedomain.com/somedir.

**Comment by fini-eng01** [comment]
We've updated our customization to the below to make it a little more configurable.

In SwaggerSpecConfig.cs, we've added a new ResolveDiscoveryUrlsUsing method that allows customization of the discovery urls in the same manner that ResolveBasePathUsing allows customization of the api base path.

![image](https://cloud.githubusercontent.com/assets/10520480/5748230/311b5584-9bf3-11e4-9273-e49bb9da911a.png)

In SwaggerUIHandler.cs, we simply return the discovery urls as configured by the DiscoveryURlsResolver.

![image](https://cloud.githubusercontent.com/assets/10520480/5748279/90595ad2-9bf3-11e4-8fc9-ebe759e758e0.png)

And in our application startup code we call the ResolveDiscoveryUrlsUsing method with our configured urls for the two subdomains. This all results again in the index.html looking like below (same as above)

![image](https://cloud.githubusercontent.com/assets/10520480/5748362/2af458a8-9bf4-11e4-99a8-a347420e000a.png)

**Comment by domaindrivendev** [comment]
I can definitely understand the desire to host docs on a separate sub-domain to your actual API. However, the approach you've described really just points a second host-name to the same website. So technically, the docs could still be accessed via the "API specific" host name (I'm guessing you just wouldn't publicize them with that URL).

Have you considered deploying the swagger-ui separately? This should be really trivial because it's built as a dependency-free bundle of web assets (https://github.com/swagger-api/swagger-ui) - all you need is a static file server. Then you can use Swashbuckle to generate and expose the raw JSON docs and have you're decoupled docs website just point to the API discovery URL.

The approach you've described feels like an edge case, at least for the intended use of SB, and right now I'm reluctant to introduce it as an additional config settings. However, if you're willing to upgrade to Swashbuckle 5.0 (currently in alpha and available as a Nuget pre-release) you can achieve your goal quite easily with a custom IDocumentFilter, without having to fork the repo.

__UpdateHostName.cs__

    public class UpdateHostName : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
        {
            // Set this to your API host name
            swaggerDoc.host = "localhost:3429";
        }
    }

__SwaggerConfig.cs__

    httpConfig 
        .EnableSwagger(c =>
            {
                // Set this to your docs host name
                c.RootUrl(req => "http://docs.localhost:3429");

                // Configure a filter that will the above with a specific API host name
                c.DocumentFilter<UpdateHostName>();

Here's more on Swashbuckle 5.0 Alpha - https://github.com/domaindrivendev/Swashbuckle/blob/swagger_2.0/README.md
