### ISSUE TITLE
Using swashbuckle with generic base controller

### ISSUE THREAD

**Issue by pashaie** [domaindrivendev/Swashbuckle#167]
I've a base controller that uses generic to implement some base operations.
The problem is that Swashbuckle enlist every model in whole system as model dependency of any controller, and that results to 1) incorrect results  2) freeze swagger ui due to huge dependency tree.

here is my base controller.

```
public abstract class BaseController<TModel, TViewModel> : ApiController
        where TModel : EntityBaseClass
        where TViewModel : EntityBaseClass
    {
        protected IBaseService<TModel> Service { get; set; }

        protected override void Dispose(bool disposing)
        {
            Service.Dispose();
            base.Dispose(disposing);
        }

        public DataSourceResult Get([System.Web.Http.ModelBinding.ModelBinder(typeof(WebApiDataSourceRequestModelBinder))]DataSourceRequest request)
        {
            return Service.GetAll().ToDataSourceResult(request).ToViewModel<TViewModel>();
        }


        public HttpResponseMessage Post(TModel model)
        {
            var result = Service.Create(model);
            if (result.Status == HttpStatusCode.InternalServerError)
            {
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new DataSourceResult {Data = new[] {result.Extra}});
            }


            var response = Request.CreateResponse(HttpStatusCode.Created, new DataSourceResult { Data = new[] { model }, Total = 1 });

            return response;
        }
]
        public HttpResponseMessage Put(int id, TModel model)
        {
            if (id == model.ID)
            {
                try
                {
                    var result = Service.Edit(model.ToViewModel<TModel>());
                    if (result.Status == HttpStatusCode.InternalServerError)
                    {
                        return Request.CreateResponse(HttpStatusCode.InternalServerError, new DataSourceResult { Data = new[] { result.Extra } });
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    return Request.CreateResponse(HttpStatusCode.NotFound);
                }

                return Request.CreateResponse(HttpStatusCode.OK);
            }
            else
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(error => error.ErrorMessage);
                return Request.CreateResponse(HttpStatusCode.BadRequest, errors);
            }
        }

        public HttpResponseMessage Delete(int id)
        {
            try
            {
                var result =Service.Delete(id);
                if (result.Status == HttpStatusCode.InternalServerError)
                {
                    return Request.CreateResponse(HttpStatusCode.InternalServerError, new DataSourceResult { Data = new[] { result.Extra } });
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            return Request.CreateResponse(HttpStatusCode.OK);
        }

    }
```

so, is it possible to make swashbuckle to work in this situation? 
here is a swagger-sepc produced by swashbuckle  for one of my controllers: http://pastebin.com/CNDdbyu9

**Comment by domaindrivendev** [comment]
I don't believe this has anything to do with the use of a generic controller. I think you would observe the same behavior if you hand-coded each concrete controller without the use of a generic base class. My guess is that the specific model classes (i.e. the different classes you're passing for TModel) have an extremely complex object graph.

By design, Swashbuckle will recursively traverse ALL "serializeable" properties on a model class. This is because Swashbuckle describes the "actual" API contract you're exposing and not the "intended" API contract. In other words, data for all the models and fields described in the outputted Swagger "can" be passed through the JSON body and WebAPI "will" deserialize them. You may not use all those values in your implementation and therefore don't "intend" them to be passed. But none-the-less, if they're serializeable, they "can" be passed and this is what Swashbuckle documents. This is the underlying philosophy - code is truth, not specification.

So ideally, if you're using Swashbuckle you should use model classes that have been tailored so that they're public properties represent the desired API contract exactly.

**Comment by pashaie** [comment]
sadly I'm not using Swashbuckle in my current projects mainly because I'm not developing in C# anymore.
But I appreciate your time and effort to solve this issue.
thanks
