### ISSUE TITLE
Conceptual question: attribute routes, route prefix and root name entry

### ISSUE THREAD

**Issue by ChristianWeyer** [domaindrivendev/Swashbuckle#185]
While looking at the sample ApiControllers available in the Dummy project, I went ahead and added a [RoutePrefix("foo")] to the AttributeRoutesController.
This is the result:

![image](https://cloud.githubusercontent.com/assets/888718/6191529/6ca8a1e6-b3aa-11e4-9110-9b5e8256450b.png)

In all honesty, I expected that the root element is no longer "AttributeRoutes" but rather "foo".
A lot of our customers (who are developers themselves) use attribute routing to alias the name and the structure of their URL and hide impl. details like the ApiController name.

Thoughts?

**Comment by domaindrivendev** [comment]
As far as the spec goes, the declaration heading (e.g. "AttributeRoutes" in your example above) represents an arbitrary grouping of operations. It's completely up to the Swagger author how they'd like to group things. Some examples, including the petstore, use the root resource for this but that is just a choice and is not an constraint imposed by the spec.

Swashbuckle defaults this to the controller name because, by it's very nature, a controller is a "grouping" of operations as chosen by the developer. However, you're free override this with your own preferred default. Check out the GroupDeclarationsBy config. setting. If you want to base this on your controllers root URL, just have your lambda inspect the controllerDescriptor.   

Assuming you're still using SB 4.x (there is a 5.0 version in alpha and available as a pre-release package), you can configure any key/value you'd like to group operations with the __GroupDeclarationsBy__. Controller name is just the default

https://github.com/domaindrivendev/Swashbuckle#groupdeclarationsby

**Comment by ChristianWeyer** [comment]
Thank you!
