### ISSUE TITLE
Defining response types for the status codes

### ISSUE THREAD

**Issue by sflanders** [domaindrivendev/Swashbuckle#204]
I'm trying to figure out how to define response type for each of the status codes.  The UI shows a "Response Model" for each status code but i can't seem to set that so the user of the api could get the metadata for it.  Typically we have a type for success and failure and would like to have this UI give them all that info.  I thought there might be a way to do this generically but haven't found the magic post on how to do that.  Hopefully this is just something i'm missing.  Thanks.

**Comment by domaindrivendev** [comment]
You should already see the response model for success responses - it's auto-generated from the actions return type (or ResponseType attribute if you're using HttpResponseMessage, IHttpActionResult etc.)

For failed responses, SB can't really auto-generate anything because there's no static way to infer what these objects might be. However, you may be able to provide the relevant information with a custom Operation Filter (see readme for more info) ...

For example, many WebApi implementations will use a shared "error" type to describe error information (validation errors etc.). If this is the case, you can easily add this to every operation description with a simple Operation Filter.

    public class AddDefaultResponse : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            var errorSchema = schemaRegistry.GetOrRegister(typeof(HttpError));

            operation.responses.Add("default", new Response
                {
                    description = "Error",
                    schema = errorSchema
                });
        }
    }

If you need more fine-grained control per operation, I would suggest decorating your actions with some custom attribute (e.g. [SwaggerResponse(typeof(SomeError))]) and then creating an Operation Filter that inspects the apiDescription for the presence of these attributes and updates the Operation accordingly.

**Comment by sflanders** [comment]
I think that will work.  One thing i noticed is that if i go the global route they only show up if i don't have any xml comments regarding response.  /// <response code="404">Not found</response>

It would be cool if here was another parameter on that for a type like:

<response code="404" type="ErrorResponse">Not found</response>

A dev could get granular and not need to write any filters or attributes if all they want is to produce meta data on the html page.

**Comment by domaindrivendev** [comment]
Closing this issue and referring you to #175 ...
