### ISSUE TITLE
Ignoring JsonProperty names

### ISSUE THREAD

**Issue by aphu** [domaindrivendev/Swashbuckle#206]
I'm having trouble having swashbuckle to ignore newtonsoft's json property attribute. It is overrriding my summary sections. Does anyone know a way around this? Thanks.

**Comment by domaindrivendev** [comment]
Can you elaborate a please?

Swashbuckle honors JsonProperty attributes by design because this reflects how the property will be serialized/deserialized. Maybe I'm missing something, but if you're using these attributes to control the corresponding JSON for properties, why would you not want the docs to consistent with this?
