### ISSUE TITLE
{{basePath}} weirdness (maybe bug?)

### ISSUE THREAD

**Issue by DotNetRockStar** [domaindrivendev/Swashbuckle#207]
In my API I have certain controllers that have a RootPrefix but not all of them.  After generating the SWAGGER json object I observed the following:

basePath = "/v2"; // had to have pulled this from a RoutePrefix from controller.

However, each and every one of my paths contained the following:
/v1/<something>
/v2/<something>

It seems that the path contains the full URI (even with the RoutePrefix) as I would expect.  However the basePath is now not needed and actually misleading because, if I read correctly, the basePath is said to be the "route prefix" to the paths which should prepend that path.  So you might expect the URL to be the following in my case:
Route: basePath + pathKey = "/v2/v1/products".
Of course this is not correct.

Is this a bug or is this by design?  If this is by design can you explain the behavior and how it should be interpreted?

Thanks!

**Comment by domaindrivendev** [comment]
Essentially, basePath is the virtual directory (if any) where your services is hosted. The routing attributes (incl. RoutePrefix) all contribute to the path for individual operations and so are never used to populate the basePath.

So, it's very strange that you're seeing basePath with a value = "/v2" unless that is actually the virtual directory for your app.

**Comment by DotNetRockStar** [comment]
Thanks for the reply.  Unfortunately I do not believe I have a virtual directory set up for my application which is yielding this.

Here is my problem.  I wrote a conversion tool to convert from swagger to a more object oriented json format that I can use to drive a razor view. The code works just fine. I am having a problem because when swagger says "this is the basePath" then what you are saying is true and my code generates the routes for my uris incorrectly making my view yield bad results.

Without diving into your code I couldent tell you why it is happening and without my edge case web api code (that I unfortunately cannot give you due to company policy) it seems you are not experiencing that problem.  Perhaps you could simply keep an eye on this and see if anyone else has this issue.  If not then perhaps it is unique to me and I can code around it somehow.

Thanks again.

**Comment by domaindrivendev** [comment]
Based on the code, it's definitely very surprising for the basePath to be populated from RoutePrefix - I can't see how this could be happening. But, you should take a quick look at the code to see if anything jumps out. Here's a little background

When a request is made for the Swagger document - e.g. http://tempuri.org/vdir/swagger/docs/v1, the website rootUrl is inferred from the host headers and virtual directory ...

    // Swashbuckle.Core/Application/SwaggerDocsConfig.cs

    public static string DefaultRootUrlResolver(HttpRequestMessage request)
    {
        var scheme = GetHeaderValue(request, "X-Forwarded-Proto") ?? request.RequestUri.Scheme;
        var host = GetHeaderValue(request, "X-Forwarded-Host") ?? request.RequestUri.Host;
        var port = GetHeaderValue(request, "X-Forwarded-Port") ?? request.RequestUri.Port.ToString(CultureInfo.InvariantCulture);

        var httpConfiguration = request.GetConfiguration();
        var virtualPathRoot = httpConfiguration.VirtualPathRoot.TrimEnd('/');
            
        return string.Format("{0}://{1}:{2}{3}", scheme, host, port, virtualPathRoot);
    }

This is in turn passed to the swagger generator ...

    // Swashbuckle.Core/Swagger/SwaggerGenerator.cs
    public SwaggerDocument GetSwagger(string rootUrl, string apiVersion)
    {

Where it's used to populate the basePath ...

    var rootUri = new Uri(rootUrl);
    ...
    basePath = (rootUri.AbsolutePath != "/") ? rootUri.AbsolutePath : null

So, this code path never even looks at any routing attributes. It's worth noting that you can configure your own root Url resolver instead of the DefaultRootUrlResolver shown above. See the __RootUrl__ config setting in the readme for more information. Is it possible you are providing your own impl for this?
