### ISSUE TITLE
Xml Documentation: Add support for specifying a parameter example value

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle#220]
In our docs we want to specify a default documentation value like 

```xml
/// <param name="filter" default="tag:swashbuckle">A filter that controls what data is returned from the server.</param>
```

**Comment by niemyjski** [comment]
I think a better term may be example or sample as it's not a default parameter value but it's a default value I'd want to be specified in the docs.

**Comment by domaindrivendev** [comment]
Closing this because, in summary, I want to move away from the use of Xml comments for setting anything other than text-based swagger properties. See #283 for my full rationale. That issue also describes a relatively simple workaround for providing samples using per-schema and per-operation filters (a SB feature which will be available shortly in the next minor release)
