### ISSUE TITLE
Base URl

### ISSUE THREAD

**Issue by niemimik** [domaindrivendev/Swashbuckle#243]
I'm using webapi in Owin iis hosted code.

Trying to set Base Url value.

This wont't do it, 

c.RootUrl(s => "https://localhost:44310");

Found this in documentation : 

SwaggerSpecConfig.Customize(c =>
{
    c.ResolveBasePathUsing(req =>
        req.RequestUri.GetLeftPart(UriPartial.Authority) +
        req.GetRequestContext().VirtualPathRoot.TrimEnd('/'));
}
 
I'm able to handle event

[assembly: WebActivatorEx.PostApplicationStartMethod(typeof(SwaggerConfig), "RegisterAfter")]

But how excalty use SwaggerSpecConfig.Customize or Where..

BR,

-mikko

**Comment by domaindrivendev** [comment]
I assume from the config. snippet above, that you're using a pre-5.x version of SB?

If you're using OWIN, you should avoid WebActivatorEx to bootstrap SB and instead configure manually in Startup.cs. This is all described in the OWIN specific section of the readme. The key point is to pull in the "Swashbuckle.Core" Nuget instead of "Swashbuckle" because the latter is for standard IIS hosted WebApi's only.

For OWIN or self-hosted, you simply reference the Core library and then manually configure as shown in the readme. Again, if you're using a pre 5.x version of SB, refer to the docs here - https://github.com/domaindrivendev/Swashbuckle/tree/v4.2.0.

Thanks
