### ISSUE TITLE
Why System.Double and System.Decimal types use the same scheme?

### ISSUE THREAD

**Issue by alexkostyanikov** [domaindrivendev/Swashbuckle#253]
Hello,
I am developing a generator tool and encountered with misunderstanding:
why do you use the same schema for System.Double and System.Decimal? 
//
CreatePrimitiveSchema method:
...
               case "System.Double":
                case "System.Decimal":
                    return new Schema { type = "number", format = "double" };
...
//
It seams to me it's wrong. How can api consumers know what a type exactly needs to use?
Thank you

**Comment by domaindrivendev** [comment]
This is not possible because the swagger-spec does not provide a way to distinguish between the two cases. Please read the section on "Data Types" ...

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md

You'll have to decide which to go with when generating your client. I would probably go with "Double" because for 99.9% of API's, 15-16 significant figures is always going to be sufficient. In fact, the default behavior of the JsonSerializer will round them down anyway.

If you feel this is too limiting, you should open an issue with the swagger spec project

**Comment by alexkostyanikov** [comment]
thanx

**Comment by alexkostyanikov** [comment]
Hi once again
I have discussed about this with swagger-spec guys. Could have a look?
https://github.com/swagger-api/swagger-spec/issues/316#issuecomment-86594998

The main point is 
"The spec does allow you to use whichever format you want, so if you want to call it float128bit or decimal, you can. It doesn't mean the tools will be able to parse it automatically though. As for the type, it's definitely number in this case."

It is described in https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types, third paragraph.

**Comment by vinson9292** [comment]
visual studio 2019 解決方案：
1.在前端Web專案中找到OpenAPIs中找到swagger.json
2.手動置換"format":"double" => "format":"decimal"
3.刪除原有連線服務，再新增連線服務，就會套用以新的swagger.json結構
