### ISSUE TITLE
XML documents bug with 5.1.1

### ISSUE THREAD

**Issue by nibras85** [domaindrivendev/Swashbuckle#270]
After upgrading to 5.1.1, when enabling XML documents, I get the following error:

500 : {"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":" at Swashbuckle.Swagger.XmlComments.ApplyXmlTypeComments.ApplyPropertyComments(Schema propertySchema, MemberInfo memberInfo)\r\n at Swashbuckle.Swagger.XmlComments.ApplyXmlTypeComments.Apply(Schema model, ModelFilterContext context)\r\n at Swashbuckle.Swagger.SchemaRegistry.CreateObjectSchema(JsonObjectContract jsonContract)\r\n at Swashbuckle.Swagger.SchemaRegistry.CreateDefinitionSchema(Type type)\r\n at Swashbuckle.Swagger.SchemaRegistry.GetOrRegister(Type type)\r\n at Swashbuckle.Swagger.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, SchemaRegistry schemaRegistry)\r\n at Swashbuckle.Swagger.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)\r\n at Swashbuckle.Swagger.SwaggerGenerator.<>c__DisplayClass7.b__4(IGrouping`2 group)\r\n at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)\r\n at Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken )\r\n at System.Web.Http.HttpServer.d__0.MoveNext()"} http://localhost:16365/swagger/docs/v1

Everything runs fine when I disable XML comments. I didn't experience this error before upgrading to the latest version.

**Comment by Hilleque** [comment]
I had the same problem and traced it down to the Apply() method of the ApplyXmlTypeComments class. Apparently, Newtonsoft's idea of what constitutes a property differs from System.Reflection; at least sometimes.

My model definition was something like:

public class MyModel
{
  public string Id;
}

In the Apply method, the following line would find 1 "property":

foreach (var entry in model.properties)

Then it calls the jsonProperty.PropertyInfo() method which looks like this:

return jsonProperty.DeclaringType.GetProperty(jsonProperty.UnderlyingName, jsonProperty.PropertyType);

That method uses reflection to get the property by name and type. Unfortunately, .NET doesn't consider the Id field to be a property, but rather a field, so it returns null. Then it blows up here because memberInfo is null:

var propertyNode = _navigator.SelectSingleNode(String.Format(PropertyExpression, memberInfo.DeclaringType.XmlCommentsId(), memberInfo.Name));

To get around this I forced the model to use properties like this:

public class MyModel
{
  public string Id { get; set; }
}

**Comment by domaindrivendev** [comment]
This should be fixed with the latest release - 5.1.2

It's worth noting that there is currently no support for using Xml comments from public fields. This fix simply prevents the null reference exception from occurring but leaves the description blank.

Full support will be added at some poin

**Comment by nibras85** [comment]
This fixed it. Thanks a lot! :+1:  :)

**Comment by adamfisher** [comment]
I am seeing this issue on 5.2.0.
