### ISSUE TITLE
Need help and samples.

### ISSUE THREAD

**Issue by dmikov** [domaindrivendev/Swashbuckle#309]
I am terribly new to Swashbuckle and the only place to connect I found is issues. The comments and documentation seems adequate, but missing samples I personally cannot use it.
My issue, we serving our api project from inside main web project, so when put WebApiConfig back global.asax.cs Swashbuckle works http://localhost/api/swagger, but when I use it from global.asax.cs in web project the http://localhost/web/api/swagger 404 me.
Now I think modifying root is the way to go, but what exactly do I put into c.RootUrl(req => GetRootUrlFromAppConfig());? I tried  "web", "web/api" that didn't work. 
Am I in the right place and what exactly needs to be put in this GetRootUrlFromAppConfig?

**Comment by domaindrivendev** [comment]
As per the docs, RootUrl requires a lambda that takes the current request and uses it to infer the URL to the root of your AspNet application. By definition, URL includes scheme, host and port components, hence why the "relative path" your trying above does not work - it's not a URL.

In the URL's you've referenced above, I'm assuming "api" is part of your routes and not a virtual directory. If this is the case, then you won't find the swagger endpoints at "http://localhost:/web/api/swagger" because they're not mounted there. Again, as per the docs, they're mounted at \<your-root-url\>/swagger which in your case would be as follows:

    http://localhost/web/swagger

If this doesn't work, then maybe you're experiencing something related to this - #305. Please let me know. Thanks

**Comment by domaindrivendev** [comment]
Regarding better samples ... I'm currently developing the next generation Swashbuckle (v6.0.0) that will target the next generation of AspNet (vNext). In this iteration, I'll be providing more functional examples in the repo. Check out the working repo for a preview ...

https://github.com/domaindrivendev/Ahoy/tree/master/test/WebSites
