### ISSUE TITLE
No support for Flagged Enum

### ISSUE THREAD

**Issue by Phille88** [domaindrivendev/Swashbuckle#320]
Hi,

I have an input parameter, which is a flagged enum:
```csharp
[Flags]
    public enum TradingType
    {
        Undefined = 0,
        Manual = 1,
        Automatic = 2,
        SemiAutomatic = 4
    }
```
But in Swagger/Swashbuckle, I can only select 1 enum value as input, while, i should be able to choose any combination of those.
How can I support this through the documentation?

Best regards,
Philippe

**Comment by domaindrivendev** [comment]
Swagger doesn't really have a first class concept for this. If it's being used as a parameter, you could describe it as an "array of enums" with "collectionFormat" set to "csv". In the swagger UI, this would result in a multi-select. On submission, the values would be serialized into a comma-separated list. This will only work if WebApi is configured to serialize enums as strings.

Swashbuckle doesn't do this out of the box because it would only make sense under certain conditions. For example, if the enum appears in a body of JSON, then it would be described as a JSON array which is incorrect and won't be correctly de-serialized into the corresponding bitmap on submission. If you have an operation which accepts an array of predefined values, then you could consider modifying you're method signature. For example,

    public IHttpResult GetByTradingTypes(TradingType tradingType)

would become ...

    public IHttpResult GetByTradingTypes(IEnumerable<TradingType> tradingTypes)

This would give you the UI behavior you're looking for out-of-the-box. However, it also may not be an option for you. If the enum is only used in parameters and is serialized as a string, another alternative would be to wire up a custom IOperationFilter (see readme) that converts the parameter description accordingly. Here's a quick example I threw together ...

    public class SupportFlaggedEnums : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            if (operation.parameters == null) return;

            var queryEnumParams = operation.parameters
                .Where(param => param.@in == "query" && param.@enum != null)
                .ToArray();

            foreach (var param in queryEnumParams)
            {
                param.items = new PartialSchema { type = param.type, @enum = param.@enum };
                param.type = "array";
                param.collectionFormat = "csv";
            }
        } 
    }
