### ISSUE TITLE
optional routes support?

### ISSUE THREAD

**Issue by Dunken** [domaindrivendev/Swashbuckle#321]
I have a route with an optional parameter:

    [Route("{categoryId?}")]
    public HttpResponseMessage Get(int? categoryId=null)

However, when I don't provide a value for `categoryId` the call includes `{categoryId?}` in the request itself...

    http://myhost/api/%7BcategoryId%7D

PS: I'm using version 5.0.4

**Comment by domaindrivendev** [comment]
This API structure is not supported by the swagger-spec - https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md.

In Swagger, an operation is uniquely identified by a combination of HTTP method and path (excluding query string). So, your action cannot be described as a single operation in Swagger.

Unfortunately, it's quite strict on this constraint. Can I ask what are the semantics of this operation? I'm assuming it might return a collection that can be optionally filtered by categoryId? If this is the case, a more typical URI structure would be as follows

/api/items?categoryId={categoryId}

This would be supported by Swagger because the optional parameter is part of the query string

**Comment by Dunken** [comment]
Thanks for clarifying it. 

It's actually a list of categories... so the structure would be like:

`/api/categories?id={categoryId}`

what looks rather weird in my opinion. Therefore I just split it in two routes:

`/api/categories`
`/api/categories/{categoryId}`
