### ISSUE TITLE
what's this line do exactly regarding basic authen in swaggerconfig file?

### ISSUE THREAD

**Issue by MarwaAhmed** [domaindrivendev/Swashbuckle#326]
@ swaggerconfig.cs:
```javascript
  GlobalConfiguration.Configuration.EnableSwagger( c =>c.BasicAuth("basic")
    .Description("Basic HTTP Authentication");
```

- when i uncommented this line i didn't see http basic authn dialog before clicking "try it out"? 
- what shall i do in order to make it work?
thanks

*linked to #319

**Comment by domaindrivendev** [comment]
This setting merely adds the "basic auth" security definition to the generated Swagger JSON. As far as I know the current swagger-ui does not do anything additional with this information - although I believe full UI support may be in the pipeline - https://github.com/swagger-api/swagger-ui/issues/764.

For now, you can add a simple customization to your swagger-ui "index.html" as described here - https://github.com/swagger-api/swagger-ui/issues/1171. I just tried it out and verified it works.

For this type of customization, you'll need to inject your own version of "index.html" instead of the version embedded in Swashbuckle (see readme https://github.com/domaindrivendev/Swashbuckle#provide-your-own-index-file).
