### ISSUE TITLE
README indicates Validator badge should show by default but it doesn't?

### ISSUE THREAD

**Issue by RPrimrose** [domaindrivendev/Swashbuckle#346]
In the README it says `By default, swagger-ui will validate specs against swagger.io's online validator and display the result in a badge at the bottom of the page.`

This isn't the behaviour I'm getting. Using a SwaggerConfig.cs without a call to either SetValidatorUrl or DisableValidator I don't see a badge at the bottom of my page. 

If I explicitly include `c.SetValidatorUrl("http://online.swagger.io/validator/");` then the badge does show up.

What's the intended behaviour here? I'm not sure if the docs need changed or if it's a code error. 

It looks like the behaviour is due to https://github.com/domaindrivendev/Swashbuckle/pull/210 having 
amended SwaggerUiConfig.cs to default to a blank validator URI.

**Comment by domaindrivendev** [comment]
Actually this is not due to the blank value set in SwaggerUiConfig. I just confirmed locally that omitting the call to SetValidatorUrl prevents the following condition (as intended).

    if (window.swashbuckleConfig.validatorUrl !== '')
        window.swaggerUi.options.validatorUrl = window.swashbuckleConfig.validatorUrl;

In this case, the default swagger-ui behavior will be to validate the spec. However, there is one caveat - if the spec is being served at localhost, then swagger-ui will still omit the validator. This is because the remote validator can only work with specs that are available over the public web.
