### ISSUE TITLE
EnableSwaggerUi and default assetPath value

### ISSUE THREAD

**Issue by jakubka** [domaindrivendev/Swashbuckle#350]
Hi,

First of all: thanks for the excellent tool! Usage is elegant and it serves its purpose really well.

We have an API-only project (no MVC, no html) and we would like to display SwaggerUi immediately after accessing the project domain. API help should be displayed after going to http://example.com, not http://example.com/swagger or something similar. 

However, with current implementation of the EnableSwaggerUi extension method, it is not possible to bind SwaggerUi directly to root, because assetPath route parameter is required and that's why requests with no assetPath always fail. With default route, it is not required to specify assetPath thanks to the little hack (in my opinion) in EnableSwaggerUi method which adds redirect from /swagger to /swagger/ui/index. Sure, I can add redirect from `/` to `/swagger`, but I would rather serve SwaggerUi directly at `/`.

Would it be possible to add route default value to the assetPath route parameter when creating the route?

Changing route registration in EnableSwaggerUi method to something like this should do the trick:

            _httpConfig.Routes.MapHttpRoute(
                name: "swagger_ui",
                routeTemplate: routeTemplate,
                defaults: new { assetPath = "index" }, // change on this line only
                constraints: new { assetPath = @".+" },
                handler: new SwaggerUiHandler(config)
            );

After this change, I will be able to register SwaggerUi to root just by calling `EnableSwaggerUi("{*assetPath}");`.

Thanks a lot for the consideration!

**Comment by jakubka** [comment]
Btw. currently I am using the following workaround to serve help at the root route:

                }).EnableSwaggerUi(c => {
                    // bind root route (http://domain.com/) to SwaggerUiHandler, so help is displayed immediately after accessing the domain. 
                    config.Routes.MapHttpRoute(
                        name: "custom_swagger_ui",
                        routeTemplate: "{*assetPath}",
                        defaults: new { assetPath = "index" },
                        constraints: new { assetPath = @".+" },
                        handler: new SwaggerUiHandler(c)
                    );
                });

**Comment by domaindrivendev** [comment]
Could you elaborate on your reasons for not just adding a redirect yourself?

For SEO and the web in general, it's a better practice for resources to have just one canonical URL, referred to by temporary or permanent redirects only. By introducing the default route parameter, there will essentially be two canonical URL's for your swagger-ui.

/swagger/ui
/swagger/ui/index

Worse still, the default version will only work if the address entered in the browser ends with a "/". This is because "index.html" uses relative paths and a relative path under "/swagger/ui" is different to a relative path under "swagger/ui/". For example, in the following screen-shot, see how none of the CSS or JS files have been loaded.

![screen-shot](https://cloud.githubusercontent.com/assets/1434343/7753025/af33df6a-ff97-11e4-8f29-60bc80f7567e.png)
