### ISSUE TITLE
Swashbuckle in Isolated Project

### ISSUE THREAD

**Issue by daniel-tiziani-tzn** [domaindrivendev/Swashbuckle#356]
Hi, 

I'd like to have my Web.Api project isolated from Swashbuckle, so I can host the documentation separated from the API itself. How can I achieve, even if I have to reference the WebApi dll's to do so (it's not an issue at all).

**Comment by domaindrivendev** [comment]
This isn't really an intended use-case, but if you're willing to jump through a few hoops it is possible. The trick is in providing Swashbuckle with an instance of IApiExplorer that corresponds to the actual API instead of the app that you're hosting Swashbuckle in.

Seeing as a couple of different people had asked about this, I decided to do a quick spike. As I said, it's not an intended use-case so I won't be providing a comprehensive solution, but I can give you some rough guidelines to get you started:

Step 1. Create an empty WebApi project to host the Swagger endpoint and swagger-ui
Step 2. Install Swashbuckle
Step 3. In your WebApiConfig.cs, replace a the default IApiExplorer, with one that's based off the config of your API (this will ultimately get passed down to SB)

    var theApiConfig = new HttpConfiguration(); // New config object to represent your API's config
    YourApi.WebApiConfig.Register(theApiConfig); // Configure via WebApiConfig in your API DLL
    theApiConfig.EnsureInitialized();

    config.Services.Replace(typeof(IApiExplorer), new ApiExplorer(theApiConfig));

Once this is done, you should be able to spin up the docs WebApi, navigate to /swagger and view the docs

Step 4. However, the host and basePath that get's returned in the Swagger JSON will still be that of the doc s app and so clicking "Try it Out" on any of the operations will return a 404. You can resolve this by wiring up a simple IDocumentFilter to adjust this accordingly.

    // UpdateHost.cs
    public class UpdateHost : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
        {
            swaggerDoc.host = "your-api-host.com";
        }
    }

    // SwaggerConfig.cs
    c.DocumentFilter<UpdateHost>();

And that should do it!

One other gotcha to look out for ... if you want the "Try it Out" functionality to work, you'll need to ensure that you actual API supports CORS requests originating from your docs website.
