### ISSUE TITLE
Error 500 with a specific method signature

### ISSUE THREAD

**Issue by daniel-tiziani-tzn** [domaindrivendev/Swashbuckle#370]
When one of my controllers define the signature below, an error 500 occours:

![image](https://cloud.githubusercontent.com/assets/10669612/7926388/507e7d58-08a8-11e5-9019-058da7adc91a.png)

*Method*

        /// <summary>
        /// Returns a NoContent (204) Result
        /// </summary>
        /// <typeparam name="T">Type of Return</typeparam>
        /// <param name="obj">Object of Return</param>
        /// <returns>Response to Return</returns>
        public NegotiatedContentResult<T> NoContent<T>(T obj)
        {
            return this.Content<T>(HttpStatusCode.NoContent, obj);
        }

**Comment by domaindrivendev** [comment]
I've not seen a WebApi action like this before ... maybe you could give a little more context so I can understand the purpose of this method. Is it part of a generic base controller that gets sub-classed for specific types of T?

**Comment by domaindrivendev** [comment]
Being a generic, there is no way that this specific action could be described in Swagger because the Swagger specification does not support the notion of generic Operations.

**Comment by daniel-tiziani-tzn** [comment]
Exactly, this is a generic method in a base class so we can customize the returns (that are not OK/NotFound/BadRequest). If you wish I can give some samples, but I'm not expecting it to document this method, but when I add this to my BaseApiController (custom class which my controllers extend), Swashbuckle fails with such error :(

Thanks for the input though!

**Comment by domaindrivendev** [comment]
OK gotcha!

So, my guess is that your "default" route configuration is somehow causing a route to be mapped to this method. This is the real problem because now WebApi thinks it represents an actual API operation, which, if I understand correctly, is not the case. Actually, I'm not surprised that SB is tripping up when it tries to generate an Operation description for this because it really is an unexpected method signature for this. 

Assuming this method is only ever invoked from sub classes, you should just change the access from "public" to "protected". This will prevent WebApi from treating it as an action and hence should resolve the issue.

**Comment by daniel-tiziani-tzn** [comment]
Thanks, it solved me problem! Congrats on the project!
