### ISSUE TITLE
Cannot Change Default Api Key Name

### ISSUE THREAD

**Issue by zeeCP** [domaindrivendev/Swashbuckle#398]
Swashbuckle  uses "api_key" as the key parameter name even when I set a different name in the configuration.
I've identified the problem in the following lines where "api_key" is hard-coded:
https://github.com/domaindrivendev/Swashbuckle/blob/c0cc5023f91080500e31720f882055658db3fc3d/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html#L93
https://github.com/domaindrivendev/Swashbuckle/blob/c0cc5023f91080500e31720f882055658db3fc3d/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html#L94

Here's my configuration:
configuration.EnableSwagger( c =>
    {
        c.SingleApiVersion("V1", "App");
        c.ApiKey("apiKey").Description("apiKey").Name("apiKey").In("query");
    })

But when I send a request, the query parameter appended is api_key and not apiKey

**Comment by mbukosky** [comment]
+1

**Comment by mbukosky** [comment]
After diving into the code a little, I found the place where the issue is occurring.

If you look into the [index.html](https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html#L93)

```javascript
function addApiKeyAuthorization(){
	var key = encodeURIComponent($('#input_apiKey')[0].value);
	if(key && key.trim() != "") {
		//This is hardcoded to only use api_key and option query
	    var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", key, "query");
	    window.swaggerUi.api.clientAuthorizations.add("api_key", apiKeyAuth);
	    log("added key " + key);
	}
}
```
Should be something more like this, but you would need to add these params to the config injection
```javascript
function addApiKeyAuthorization(){
	var key = encodeURIComponent($('#input_apiKey')[0].value);
	if(key && key.trim() != "") {
	    var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("%(ApiKeyName)", key, "%(ApiKeyIn");
	    window.swaggerUi.api.clientAuthorizations.add("api_key", apiKeyAuth);
	    log("added key " + key);
	}
}
```

I was personally able to workaround this by overloading the index page with my custom page.

```csharp
// Use the CustomAsset option to provide your own version of assets used in the swagger-ui.
// It's typically used to instruct Swashbuckle to return your version instead of the default
// when a request is made for "index.html". As with all custom content, the file must be included
// in your project as an "Embedded Resource", and then the resource's "Logical Name" is passed to
// the method as shown below.
//
c.CustomAsset("index", typeof(SwaggerConfig).Assembly, "FooBar.SwaggerUI.index.html");
```
This is the section I changed in my index.html
```javascript
function addApiKeyAuthorization(){
	var key = encodeURIComponent($('#input_apiKey')[0].value);
	if(key && key.trim() != "") {
		//var apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("api_key", key, "query");
		apiKeyAuth = new SwaggerClient.ApiKeyAuthorization("MyKey", key, "header");
	    window.swaggerUi.api.clientAuthorizations.add("api_key", apiKeyAuth);
	    log("added key " + key);
	}
}
```

I will see if I can put together a PR to fix this issue.

**Comment by domaindrivendev** [comment]
I would suggest maybe holding off on the PR. In the next major version, I'll be removing the UI stuff from the config API and just recommend that you provide a custom "index.html" for any UI customizations.

This reduces the maintenance overhead for Swashbuckle as it won't need to provide its own abstraction layer around the swagger-UI settings. Furthermore, it will be easier to find answers to questions like this because you would get answers on an swagger forum

**Comment by mbukosky** [comment]
Sure thing. I am almost done with my changes. If you want them, just let me know and I will submit a PR, if not I look forward to the next release.

**Comment by akirayamamoto** [comment]
+1
I just provided a custom index.html file to fix this.
Thanks for letting me know how to fix this.

**Comment by lukemcgregor** [comment]
+1 why would you not include this change in the default template?

**Comment by comino** [comment]
+1 - yeah why?

**Comment by Pharylon** [comment]
+1 Seems simple, why not do it?
