### ISSUE TITLE
Need to show specific url on swagger UI using configuration

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#399]
I have requirement that I want to show specific URLs on Swagger UI. For example, I want to show only get action methods from all controllers in web api. Could I do that with any configuration in swashbuckle.

**Comment by davetransom** [comment]
First option: you can control what is included via the `ApiExporerSettingsAttribute` (see https://github.com/domaindrivendev/Swashbuckle/issues/153#issuecomment-69537898)

	[ApiExplorerSettings(IgnoreApi=true)]
	public class MyController : ApiController

Otherwise, you should be able to remove the other verbs with a document filter - something along the lines of:

	class RemoveVerbsFilter : IDocumentFilter
	{
		public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
		{
			foreach (PathItem path in swaggerDoc.paths.Values)
			{
				path.delete = null;
				path.head = null;
				path.options = null;
				path.patch = null;
				path.post = null;
				path.put = null;
			}
		}
	}

and in your swagger config:

	...EnableSwagger(conf => 
	{
		// ...

		conf.DocumentFilter<RemoveVerbsFilter>();
	});

There might be other approaches to do it as well.

**Comment by domaindrivendev** [comment]
The approaches above (thanks to @davetransom) should allow you to do this
