### ISSUE TITLE
Add Xml documentation comments to library code

### ISSUE THREAD

**Issue by jnonce** [domaindrivendev/Swashbuckle#407]
Add [XML Documentation Comments][1] to public types and members.  Like:

```cs
/// <summary>
///  This is a comment!
/// </summary>
public class MyClass{}
```

This would make using the library easier as the summaries would be shown in Intellisense.

[1]: https://msdn.microsoft.com/en-us/library/vstudio/b2s063f7(v=vs.120).aspx

**Comment by davetransom** [comment]
I believe the comments on a class are actually added to the swagger json document - but swagger-ui  doesn't currently display them. Is it worth suggesting it to them?

I've used [this dirty hack](https://gist.github.com/davetransom/1f2bf02c63a4922fca33) in a previous project to overcome this - it works, but isn't ideal.

**Comment by domaindrivendev** [comment]
@jnonce - correct me if I'm wrong but I believe you're referring to XML comments within the actual Swashbuckle code. You're suggesting this would make it easier to use the library, in particular when using the configuration interface in SwaggerConfig.cs?

Philosophically, I'm not a huge fan of extensive commenting throughout code and instead I strive to write code that is readable and intention-revealing on it's own. The main reason being that comments go out of date easily.

So, while I do understand the value in what you're asking for, I'm going to punt on it for the moment because I don't want to take on the overhead of keeping comments up-to-date.

Thanks
