### ISSUE TITLE
TokenName option missing in Swashbuckle (latest version)

### ISSUE THREAD

**Issue by pushpabrol** [domaindrivendev/Swashbuckle#425]
This was available in pervious version (4.1.0)...example below...This means the TokenName is hard coded as access_token :(

 GrantTypes = new GrantTypes
                    {
                        ImplicitGrant = new ImplicitGrant
                        {
                            LoginEndpoint = new LoginEndpoint
                            {
                                Url = issuer.TrimEnd('/') + "/authorize"
                            },
                            TokenName = "id_token"
                        }

**Comment by domaindrivendev** [comment]
The 4.x line was using version 1.2 of the Swagger specification. The 5.x line uses Swagger 2.0 which no longer supports "tokenName" in the auth descriptions.

A quick browse of the Swagger spec repo led me to the following issue, where they cited their rationale for omitting it

https://github.com/swagger-api/swagger-spec/issues/37

In summary, the OAuth2 spec itself does not allow for flexibility around the token name and so they decided against allowing for it in the Swagger 2.0 spec.

I know this may not be the answer you'd like, but your issue is related to a constraint in the Swagger spec and not Swashbuckle.

**Comment by Mike-Bell** [comment]
I know this is 3 years old, but for posterity's sake, you can work around this. You can follow the instructions here to inject a custom JS script into the swagger workflow: https://github.com/domaindrivendev/Swashbuckle#injecting-custom-content

You can then modify the tokenName property name with JavaScript like so:

`window.swaggerUiAuth.tokenName = 'id_token';`

PS this is a hack, and I wouldn't rely on it to work forever, but it gets the job done
