### ISSUE TITLE
Odata Queryable URL Parameters

### ISSUE THREAD

**Issue by Lswith** [domaindrivendev/Swashbuckle#427]
I have enabled odata queryable url parameters for my api controller. Swashbuckle doesn't include the optional parameters in the request in swagger.

**Comment by domaindrivendev** [comment]
The first thing to note here is that Swashbuckle is built on top of WebApi's built-in metadata layer - ApiExplorer. Unfortunately, this metadata layer does not provide descriptions for OData controllers or actions with OData behavior enabled via the Queryable / EnableQuery attributes. You can track the issue here:

https://github.com/OData/WebApi/issues/94

However, SB does provide a range of extensibilty points that could be used to address your issue. For your case, you could wire up a custom OperationFilter (see readme) that will inspect each action and, if decorated with Queryable, add the standard query params to the corresponding Swagger Operation. Here's some sample code to get you started ...

    public class AddODataQueryParams : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            var attribute = apiDescription.ActionDescriptor
                .GetCustomAttributes<EnableQueryAttribute>()
                .FirstOrDefault();

            if (attribute == null) return;

            // Add standard OData query params here
            if (operation.parameters == null)
                operation.parameters = new List<Parameter>();

            operation.parameters.Add(
                new Parameter
                {
                    name = "$skip",
                    @in = "query",
                    type = "number",
                    format = "int32",
                    description = "Skips the first n results"
                }
            );

            operation.parameters.Add(
                new Parameter
                {
                    name = "$top",
                    @in = "query",
                    type = "number",
                    format = "int32",
                    description = "Returns the first n results"
                }
            );

            // and so on ...
        }
    }

This is a simplified example and things could certainly get more complicated if you want to account for the different options available with the Queryable attribute. If you come up with a good solution, you may want to consider packaging it as a Swashbuckle extension (e.g. Swashbuckle.OData) so that others can use it.
