### ISSUE TITLE
DateTimeOffset generates an invalid date format

### ISSUE THREAD

**Issue by tharris29** [domaindrivendev/Swashbuckle#462]
When using a property of type DateTimeOffset the time that is generated in the schema looks like 

````j
 "TimeStampWithUtcOffset": "2015-08-19T10:54:22.430Z"
````
when it should look like
````j
 "TimeStampWithUtcOffset": "2015-08-19T11:53:42.7757491+01:00"
````
I believe the following code is the cause. We set all date-time properties as the same format.

https://github.com/domaindrivendev/Swashbuckle/blob/e74cf10c092934c3ca02b5102138ac8ff9f31c75/Swashbuckle.Core/Swagger/SchemaRegistry.cs#L156

https://github.com/domaindrivendev/Swashbuckle/blob/c0cc5023f91080500e31720f882055658db3fc3d/Swashbuckle.Dummy.Core/SwaggerExtensions/swagger-client.js#L1159

I have managed to work around this with the follow snippet. This is not a long term solution as different end points will require different schemas.

 ````c#
    public class SchemaFilter : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
        {
                schema.example = new { TimeStampWithUtcOffset = DateTimeOffset.Now};
        }
    }
````

Happy to discuss and create a PR with some guidance.

**Comment by domaindrivendev** [comment]
Swasbuckle doesn't provide examples out-of-the-box - by design, this is left up to the application. The samples you are seeing are automatically generated by the swagger-ui, based off the schema "format" property.

However, in your Swagger config, you can easily hook in a provide your own custom Schema for all occurrences of that specific type. I think this would be an easy and sustainable solution for you:

    c.MapType<DateTimeOffset>(() =>
        new Schema {
            type = "string",
            format = "date-time",
            example = DateTimeOffset.Now
        }
    );

**Comment by tharris29** [comment]
:+1:
