### ISSUE TITLE
Swashbuckle + Glimpse.MVC = blank documentation

### ISSUE THREAD

**Issue by svickers** [domaindrivendev/Swashbuckle#468]
I was having the same problem as #184 where the discovery URL yielded no API endpoints.  Pulling my hair out trying to figure out what was going wrong I started a fresh project and gradually started migrating route config, cors settings, oauth, etc etc.  Finally figured out adding the glimpse.mvc package caused the problem.

**Comment by UtkarshPatkar** [comment]
I am having the same issue. Swashbuckle was working fine for me till I added Glimpse.
Once I add the Glimpse module following call starts returning 0. 
GlobalConfiguration.Configuration.Services.GetApiExplorer().ApiDescriptions;

If i comment glimpse module it works fine.

**Comment by UtkarshPatkar** [comment]
After further analysis here is what seems to be a problem:
1. Glimpse adds castle proxies on top of HttpWebRoute. So HostedHttpRouteCollection is collection of **RouteProxy and not HttpWebRoute**.
2. APIExplorer class has **FlattenRoutes** method which does a foreach loop over HostedHttpRouteCollection.
3. **GetEnumerator** implementation of **HostedHttpRouteCollection** specifically look for HttpWebRoute. See the code below. Since glimpse has added proxies, enumerator always returns 0 routes!!

```

        public override IEnumerator<IHttpRoute> GetEnumerator()
        {
            // Here we only care about Web API routes.
            return _routeCollection
                .OfType<HttpWebRoute>()
                .Select(httpWebRoute => httpWebRoute.HttpRoute)
                .GetEnumerator();
        }

```
Any work around or suggested solution?

**Comment by domaindrivendev** [comment]
SB is built on top of WebApi's metadata layer - ApiExplorer. However, it seems there's a bug in Glimpse that breaks ApiExplorer. See the following for more info and a suggested workaround:

https://github.com/Glimpse/Glimpse/issues/520

Closing as it's not a SB issue.
