### ISSUE TITLE
Could not find Parmeter in Post Request

### ISSUE THREAD

**Issue by RahulRParmar** [domaindrivendev/Swashbuckle#484]
Hi
I have successfully configured swagger project for our environment.
But currently I am getting one issue I couldn't find request parameter for POST[form-data] method So not able to test Post methods. I can able to see request parameter for GET Method.

**Comment by RahulRParmar** [comment]
Hey Any updates on above issue?

**Comment by RahulRParmar** [comment]
Hi
I have successfully configured swagger project for our environment.
For the Post Request 
It not showing Body textare for POST request where i can enter input
Json of Api call?

**Comment by domaindrivendev** [comment]
There must be something specific about your setup because I have not yet observed any issue with POST parameters.

Could you provide more detail - perhaps your controller action signature?

**Comment by RahulRParmar** [comment]
Hi
My Controller's action signature are as below
 [AcceptVerbs("POST")]
        public ResponseObject<ClientResponse2> GetClientByName()
        {}

For the above methods we are not getting request parameter.

It would be great you can give me some guidance to resolve.

**Comment by domaindrivendev** [comment]
You don't have any parameters in the action signature. I guess you're accessing the body via the controllers Request property instead of through a parameter.

Any particular reason why you're doing it this way? Not that there's anything wrong with it but it's less explicit and limits the metadata available to tools like SB.

For example, in this case, SB has know way of knowing that there should be a parameter for this action. It could assume, being a POST, but that would be a bad assumption because Http does allow POST's without a body. If you update your action signature as follows, you'll see a textarea for the parameter.

    public  ResponseObject GetClientByName(JObject body)

**Comment by domaindrivendev** [comment]
FYI, if there's a specific reason why you're not using parameter binding, I'd be really interested to understand the rationale. But also, because I can describe a simple SB extension to always include a body parameter for all POST operations, regardless of the action signature.

**Comment by RahulRParmar** [comment]
Thank you very much. I will update you if any.
Thanks again for your response.
