### ISSUE TITLE
Custom ParameterBindingAttribute causes methods to be ignored

### ISSUE THREAD

**Issue by raaga123** [domaindrivendev/Swashbuckle#518]
Hi,

Our application needs to use a custom variation of the FromUri parameter attribute, which we are calling FromDecodedUri. Is there a way to notify Swagger/Swashbuckle of the existence of this attribute? Right now, any method whose parameters are decorated with this attribute are simply ignored when the API doc is generated.

Thanks,
     Lyn

**Comment by raaga123** [comment]
To clarify:

FromUri is a value of the ApiParameterSource enumeration, which is defined in System.Web.Http.Description. Swagger copes with parameters annotated with [FromUri] just fine.

One of our developers created a new attribute of type System.Web.Http.ParameterBindingAttribute. This attribute is called FromDecodedUri, and is intended to work like FromUri except that the parameter is passed through a filter to remove special characters.

The new parameter annotation [FromDecodedUri] behaves as expected in the program, but it seems to confuse Swashbuckle. Any method with a parameter annotated with this attribute simply does not appear in the json output

**Comment by domaindrivendev** [comment]
When Swashbuckle encounters an ApiParameterDescription (provided via WebApi's built-in metadata layer - ApiExplorer) it checks the "Source" property to determine if the parameter should be described as path, query, body etc. However, it's likely that your custom binding implementation is causing this property to return "Unknown" instead of "FromUri" and this means Swashbuckle can't possibly know how to describe the parameter.

In fact, I implemented a HttpParameterBinding as described here - http://www.asp.net/web-api/overview/formats-and-model-binding/parameter-binding-in-aspnet-web-api and sure enough noticed that the resulting ApiParameterDescription.Source was returning "Unknown". So, I dug a little deeper into the WebApi source to see how that property is getting populated and discovered that it all boiled down to the following extension method:

        public static bool WillReadUri(this HttpParameterBinding parameterBinding)
        {
            if (parameterBinding == null)
            {
                throw Error.ArgumentNull("parameterBinding");
            }

            IValueProviderParameterBinding valueProviderParameterBinding = parameterBinding as IValueProviderParameterBinding;
            if (valueProviderParameterBinding != null)
            {
                IEnumerable<ValueProviderFactory> valueProviderFactories = valueProviderParameterBinding.ValueProviderFactories;
                if (valueProviderFactories.Any() && valueProviderFactories.All(factory => factory is IUriValueProviderFactory))
                {
                    return true;
                }
            }

            return false;
        }
    }

If this returns true, then the ApiParameterDescription.Source will be assigned the value "FromUri". So, your custom binding needs to meet the following requirements.

1) Implement IValueProviderParameterBinding
2) Return a ValueProviderFactory of type IUriValueProviderFactory

To do this, you would need to modify your custom binding to use value providers. For example:

    public class FromDecodedUriAttribute : ModelBinderAttribute
    {
        public override IEnumerable<ValueProviderFactory> GetValueProviderFactories(HttpConfiguration configuration)
        {
            yield return new DecodedUriValueProviderFactory();
        }
    }

    public class DecodedUriValueProviderFactory : ValueProviderFactory, IUriValueProviderFactory
    {
        public DecodedUriValueProviderFactory()
            : base()
        {}

        public override IValueProvider GetValueProvider(HttpActionContext actionContext)
        {
            return new DecodedUriValueProvider(actionContext);
        }
    }

    public class DecodedUriValueProvider: IValueProvider
    {
        private HttpActionContext _actionContext;

        public DecodedUriValueProvider(HttpActionContext actionContext)
        {
            _actionContext = actionContext;
        }

        public bool ContainsPrefix(string prefix)
        {
            return false;
        }

        public ValueProviderResult GetValue(string key)
        {
            // Pul the value out of _actionContext
        }
    }

**Comment by daniel-m-decker** [comment]
My team is using injecting a custom DocumentFilter to completely wipe and replace any existing paths (SwaggerDocument.Paths) and replace them with our own implementation, and this is a great place to write your own checks for the existence custom attributes. At a high-level, from the assembly you get a list of all controllers types deriving form ApiController, iterate through them, iterate through each controller's method and build a new PathItem and operation.

**Comment by razonrus** [comment]
It is not a Swagger problem. After correct settings for standart ApiExplorer all must work.
Similar question: https://stackoverflow.com/questions/46788440/route-with-custom-type-doesnt-show-up-in-swagger
Example with my solution: https://stackoverflow.com/a/47123965/908936
