### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by turowicz** [domaindrivendev/Swashbuckle#532]
Is there a way of having the static content in a CDN? Currently the app hosts all of them which is slowing it down quite a bit.

**Comment by turowicz** [comment]
All that needs to happen is to load jquery and swagger-ui scripts from:

https://cdnjs.com

**Comment by heldersepu** [comment]
This change I believe we will need to modify only one file:
https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html

I was looking on the cdnjs and could not find a few of the items:
```html
  <script src='lib/jquery-slideto-min-js' type='text/javascript'></script>
  <script src='lib/jquery-wiggle-min-js' type='text/javascript'></script>
  <script src='lib/jquery-ba-bbq-min-js' type='text/javascript'></script>
```
The backbone-min seems to have some customizations on the version we use: 
https://github.com/swagger-api/swagger-ui/blob/64dc3060b3700b12e466f8d67b7d7ec3574b015f/lib/backbone-min.js
and here is the version on the CDN:
https://cdnjs.com/libraries/backbone.js/1.1.2

...
I was doing some benchmarks on my test (hosted on Azure) and  on average it fully loads in ~1.2 seconds with caching disabled.
With all that I think it will be too much trouble to get all the swagger-ui parts from a CDN.

BUT we should consider **bundling** all the CSS and JS into individual files, that way it will be 2 requests instead of 15+

**Comment by heldersepu** [comment]
Looks like the new version (3.x) of swagger-ui is doing the bundle ...
http://petstore.swagger.io/swagger-ui-bundle.js

**Comment by domaindrivendev** [comment]
Swashbuckle is fundamentally a Swagger generator that merely leverages the swagger-ui library as it's documentation front-end. Therefore, I generally consider UI enhancements to be out of scope.

With that said, Swashbuckle does provide a means to inject your own index.html (see readme) for the swagger-ui and therefore it would be relatively trivial to do this and reference the CDN assets, giving you the latency benefits you require.
