### ISSUE TITLE
Pretty print JSON output

### ISSUE THREAD

**Issue by mchambaud** [domaindrivendev/Swashbuckle#541]
Is it possible to output pretty JSON? I found this but I think it's not valid with Swashbuckle

https://github.com/swagger-api/swagger-core/issues/810

**Comment by GDoronin** [comment]
Hi,

`Swashbuckle` doesn't use` swagger-core` to generate the JSON documentation.
So yes, `swagger.pretty.print` has no effect.

However, as I see from the source code - it is possible to prettify `Swashbuckle` JSON output simply configuring `JsonMediaTypeFormatter` to use `Formatting.Indented` here https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Application/SwaggerDocsHandler.cs#L54-L58

```csharp
SerializerSettings = new JsonSerializerSettings
{
	NullValueHandling = NullValueHandling.Ignore,
	Formatting = Formatting.Indented,
	Converters = new[] { new VendorExtensionsConverter() }
}
```

But since this prettifying should be configurable (turn off/on), one should extend `SwaggerDocsConfig` with some kind of a flag `bool _prettifyJsonOutput` or smth like this.

Why I know the answer to your question?
Because I would to have pretty output too and also made some investigation :)

Les't wait for the answer from @domaindrivendev and maybe he, you or me will add this feature if approved.

**Comment by GDoronin** [comment]
@mchambaud just pushed the PR #577

**Comment by mchambaud** [comment]
@GDoronin Thanks mate, much appreciated!

**Comment by domaindrivendev** [comment]
See 5.3.1
