### ISSUE TITLE
Using Swashbuckle in a developer site

### ISSUE THREAD

**Issue by bloudraak** [domaindrivendev/Swashbuckle#545]
Assume for a moment I have several websites exposing APIs, each implemented as an ASP.NET website. For numerous reasons, these sites don't have any user interface. 

* xxx.example.com
* yyy.example.com
* zzz.example.com

Now assume that I'd like developers to visit a single site developers.example.com (also an ASP.NET application) to view the documentation of the different APIs. In essence, this is the only site that will display the Swashbuckle UI.  

I modified the Visual Studio project of developers.example.com to reference each of the projects that implement an API. I then modified developers.example.com to use one of the XML documentation files (e.g. xxx.example.com).

When I visit https://developers.example.com/api/swagger, I do not see the documentation of xxx.example.com.

This raises a couple of questions:

* How do I get Swashbuckle in the developers.example.com to display the documentation of xxx.example.com? 
* How do I get Swashbuckle in the developers.example.com to display the help of all the APIs (xxx.example.com, yyy.example.com, zzz.example.com).

**Comment by domaindrivendev** [comment]
One UI for multiple API's isn't supported as a first-class concept in Swashbuckle. However, there are lots of ways to get creative and make this happen. If I'm understanding your use-case correctly, I think this issue is really a dup of #125 so I'm going to close this and refer your there.

In summary though, I would recommend that you have your developers.example.com website make HTTP requests to get the corresponding Swagger descriptions from each of the API's. You can then update swagger/index.html to include a drop-down for each of the API's and when one is clicked, refresh the page based on the associated Swagger. Take a look at the markup from this line on for inspiration - this is for Multiple versions of the same API but the principle should still apply:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/MultipleVersions/Swagger/index.cshtml#L106

**Comment by Xavina** [comment]
Hi,

The last link is broken! I think that this is what I need!

Thanks,
