### ISSUE TITLE
GroupActionsBy and tags -- details?

### ISSUE THREAD

**Issue by raaga123** [domaindrivendev/Swashbuckle#565]
Hi, all -

I need to use explicit tags to group my API methods in Swashbuckle, and the only information I've been able to find out about how to do this is:

    Each operation be assigned one or more tags which are then used by consumers for various 
    reasons. For example, the swagger-ui groups operations according to the first tag of each 
    operation. By default, this will be controller name but you can use the "GroupActionsBy" option 
    to override with any value.
    // c.GroupActionsBy(apiDesc => apiDesc.HttpMethod.ToString());

Is there any information out there on how to use this feature? The two basic questions I have are:

    1. What is "apiDesc" in the commented call above? 

    2. How do I assign a tag (and description) to a set of methods?

Thanks in advance for your patience with the naive.... :)

-- Lyn

**Comment by raaga123** [comment]
OK, I found an example that helps with the GroupActionsBy call. I could still use some specifics about how to assign tags so that they're included in the auto-generated documentation, though.

**Comment by domaindrivendev** [comment]
apiDesc is an instance of ApiDescription which is a WebApi abstraction that describes an individual action (routes, HTTP method, parameters etc.). The GroupActionsBy method allows you to provide your own "strategy" for tagging (and hence grouping) each action in your API, based on the provided ApiDescription metadata. So, the example in the readme that you've referenced above, will group your actions by HTTP method instead of controller name (the default).

If you read through the swagger specification, you'll see that tag descriptions require a little more work. In addition to assigning the tag name to the operation (as described above) you'll need to define a global definition at the SwaggerDocument level for each tag. You can do this by wiring up a custom IDocumentFilter as described in the readme.
