### ISSUE TITLE
Is it possible to render Response ReasonPhrase ?

### ISSUE THREAD

**Issue by all4Git** [domaindrivendev/Swashbuckle#623]
I've already posted this issue on swagger-ui issues [here](https://github.com/swagger-api/swagger-ui/issues/1890), but maybe this is more a swashbuckle question :

> I use Swashbuckle with my .NET web api projet.
I added a Filter to my web api, to authorize only https requests, not http ones.
When an http request is sent, the response is 403, with this additionnal ReasonPhrase : "HTTPS is required". But when I call an operation through SwaggerUI, I can see the 403 in the "Response code" section, but the ReasonPhrase appears nowhere (there is no "Response reason" section).
When I call directly the operation with its URL, I can see the 403 and the reason phrase.
As 403 is also used for other forbidden reasons, I would have liked to specify the ReasonPhrase for each case, to help client to see what the problem is. I think it would be something useful for the client.
Is there a way to add the ResponsePhrase in SwaggerUI, when rendering a response 
Thanks.

**Comment by VisualBean** [comment]
![reasonphrase](https://cloud.githubusercontent.com/assets/5294032/12780647/5dde77bc-ca6f-11e5-825f-58702fc79886.png)
The only thing I can think if is the "Response Messages" section I'm using XML comments like so
<response code=403>HTTPS is required</response> - I've added this to all actions, but it could be added through an operation filter

**Comment by domaindrivendev** [comment]
The answer from @VisualBean sounds like an acceptable solution.

**Comment by all4Git** [comment]
Sorry for my late answer. Thanks @VisualBean

**Comment by ladimolnar-nf** [comment]
@domaindrivendev: I think this should be reopened. VisualBean's response does not address the issue. It is true, one can document all possible values for ReasonPhrase that are associated with a status code but that is not the issue. The issue is that when trying the API out I would like to see what the ReasonPhrase is when getting back an error code. After invoking the API, the ReasonPhrase should be rendered along with the status code.
