### ISSUE TITLE
Add meta tags to default swagger-ui index page

### ISSUE THREAD

**Issue by all4Git** [domaindrivendev/Swashbuckle#668]
Hi,
I would like to force the swagger-ui index page not to be cached, adding these meta tags in the head section : 
META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE"
META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE"
META HTTP-EQUIV="EXPIRES" CONTENT="0"
How can I do that ?
I would like to use the native index page, not using my own index file through CustomAsset functionnality. 
Is there a way to add meta tags to the default index swagger-ui page ?
Thanks.

**Comment by VisualBean** [comment]
You could inject some javascript that inserts the tags you need, but it is still a customAsset

**Comment by all4Git** [comment]
Thanks @VisualBean 

Problem is javascript injected with "InjectJavaScript" is executed after the page is loaded.
For such elements as meta, it can not be done this way.
I just tried to add these code in one javascript file I inject with "InjectJavaScript" : 
`var meta = document.createElement('meta');
        meta.httpEquiv = "CACHE-CONTROL";
        meta.content = "NO-CACHE";
        document.getElementsByTagName('head')[0].appendChild(meta);`
But as expected, it has no effect.

I think the only way to add meta tags without injecting a custom index page would be to add these tags with a dedicated method in the SwaggerConfig Register method.
But I did not see any methods to do that in the documentation.
It would be something like : 
c.InjectMeta(thisAssembly, "<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE>");

I don't know if it is something that can be added to upcoming swashbuckle versions ?

**Comment by domaindrivendev** [comment]
Fundamentally, Swashbuckle is a Swagger JSON generator. To provide a complete documentation solution, it ships with an embedded version of the [swagger-ui](https://github.com/swagger-api/swagger-ui). However, the value-add is really in the generator. It would actually be quite trivial to host the swagger-ui assets yourself and simply point to the Swagger JSON endpoint generated by Swashbuckle.

For these reasons, direct UI enhancements are outside the current scope of the Swashbuckle project. With that said, I will endeavor to keep the embedded version up-to-date so that new features implemented by the swagger-ui folks are made available through Swashbuckle. Although it is currently a major version behind :(

But, with all that said, you CAN still achieve your goal by simply injecting your own of the index.html page and applying your meta tags there. See the [readme](https://github.com/domaindrivendev/Swashbuckle#provide-your-own-index-file) for instructions.
