### ISSUE TITLE
Uncaught ReferenceError: JSONEditor is not defined

### ISSUE THREAD

**Issue by replaysMike** [domaindrivendev/Swashbuckle#669]
After upgrading to v6.0.0-rc1-final and core 5.3.2 everything broke and throws a console error: Uncaught ReferenceError: JSONEditor is not defined

Any ideas? Missing some dependencies maybe?

**Comment by wekempf** [comment]
I just had the same issue, and tracked down what my problem was. I don't know that it's the same problem you're experiencing, though. Our issue was that we'd provided a custom index.html file. This file was not compatible with the newer version of Swashbuckle/Swagger-UI. Among other differences it was missing a script tag for lib/jsoneditor-min-js. This seems like a very error prone way for customizing the display, but it's the only method we're aware of. I don't know if this information will help you or not, but figured I should supply it.

**Comment by replaysMike** [comment]
Thank you yes this is quite likely the same issue as we also use a custom index.html. I'll give that a shot today, thanks for the suggestion!

**Comment by domaindrivendev** [comment]
This was an unfortunate "breaking change" to those of you using custom "index.html" files. Because the swagger-ui introduced a new dependency on JSONEditor, you could argue that it's a breaking change on their end and this should have been indicated with a new major version which would have made me think twice including it with the SB 5.x line.

On the flip side, a new major version seems like overkill too. For now, I'm going to apologize to you all for the breaking change and close the ticket.

**Comment by synic** [comment]
So.. what exactly is the fix here?

**Comment by domaindrivendev** [comment]
Update your custom index file to pull in the required script (i.e. jsoneditor) as shown here https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html
