### ISSUE TITLE
How are produces/consumes populated?

### ISSUE THREAD

**Issue by raaga123** [domaindrivendev/Swashbuckle#692]
Sorry about the naive question, but I haven't been able to find an answer to this yet....

How are the MIME types in the produces/consumes elements determined? We're using Swashbuckle to generate documentation for our REST API, and for the most part it works great, but the JSON rendering shows many operations with a list of multiple types in "Produces" and "Consumes". Where do these come from? Our API accepts input and produces output only in JSON format.

**Comment by raaga123** [comment]
Since we don't really need those sections, I can probably write an OperationFilter to remove them, but I was wondering if there was a more straightforward solution.

**Comment by VisualBean** [comment]
If you are using webapi, those come from the global config formatters - you can add remove them in the webapiconfig.cs file

**Comment by domaindrivendev** [comment]
@VisualBean is correct. In fact, if you're not currently doing this then I believe that your API does in fact support XML even though that's clearly not your intention.

With SB, it's possible to tweak the docs via the various supported filters but where possible, I think it's better practice to be more explicit with your implementation so that the docs are bound directly to actual behavior. This is a prime example - SB isn't wrong in it's description because as I said, I think you'll find that your API does support XML. In other words, SB is agnostic of your intentions. It's only interested in describing the "actual" behavior your API currently exhibits.
