### ISSUE TITLE
Update code for ading default `200` or `204` responses

### ISSUE THREAD

**Issue by dariusdamalakas** [domaindrivendev/Swashbuckle#726]
[SwaggerGenerator.CreateOperation](https://github.com/domaindrivendev/Swashbuckle/blob/953f9803bdf4a5051dd4ad90f8a6bc0ad8b6af3b/Swashbuckle.Core/Swagger/SwaggerGenerator.cs#L141) should be updated to use a a filter for addding default `204` or `200`  responses instead of hardcoding this.

As it is now, if `responseType` is `IHttpActionResult`, then `200` code would be added by default, which is incorrect - the result can be of any type including no content (204). 

The issue is that it is not possible to override this behaviour.

**Comment by domaindrivendev** [comment]
When you use IHttpActionResult, you have to give Swashbuckle a few hints because it can't possibly infer something that's only determined at run-time. In fact, WebApi has a built-in attribute for this which handles many cases.

    [ResponseType(typeof(void))] // will be described as 204 - No Content
    public IHttpActionResult Head()
    ...

    [ResponseType(typeof(ProductDto))] // will be described as 200 - Success
    public IHttpActionResult Create()
    ...

For these case - SB reflects the default behavior of WebApi. That is, when you return a void, the response code will be 204 and when you return an object, the response code will be 200.

However, the current version of WebApi does not provide any attributes for describing "error" response codes. For this, SB layers on some additional attributes:

    [ResponseType(typeof(ProductDto))] // will be described as 200 - Success
    [SwaggerResponse(400, "Invalid request")]
    public IHttpActionResult Create()
    ...

Finally, if you're setting explicit response within your action methods (as opposed to falling back to the WebApi default behavior) - you'll also need to disable SB's default behavior and describe all response (including the success case) explicitly:

    [SwaggerResponseRemoveDefaults]
    [SwaggerResponse(201, "Created", typeof(ProductDto))]
    [SwaggerResponse(400, "Invalid request")]
    public IHttpActionResult Create()
