### ISSUE TITLE
Spec says to use swagger.json

### ISSUE THREAD

**Issue by Vaccano** [domaindrivendev/Swashbuckle#733]
I was trying to integrate my Swashbuckle generated Swagger docs with an external tool.   However it would not work with the tool (the tool is called Outsystems).

The creators of the tool told me that the reason is that the json for the swagger data is supposed to be in a file called `swagger.json`.

I checked the [spec ](http://swagger.io/specification/)and it does mention that: 

>File Structure

>The Swagger representation of the API is made of a single file. However, parts of the definitions can be split into separate files, at the discretion of the user. This is applicable for $ref fields in the specification as follows from the JSON Schema definitions.

>**By convention, the Swagger specification file is named swagger.json.**

But my json is in https://MyDomain/MyService/swagger/docs/v1

Is there a way to to configure swashbuckle to put the swagger json in a file called swagger.json?

**Comment by domaindrivendev** [comment]
You're correct, the recommended convention is to use a file named swagger.json. This will be the default in the next major version (6.0.0) of Swashbuckle (targeting Asp.Net Core). 

In the meantime, you can customize the routes as described in the readme - https://github.com/domaindrivendev/Swashbuckle#custom-routes

One gotcha to look out for - you'll need to add the following setting to your web.config

    <system.webServer>
        <modules runAllManagedModulesForAllRequests="true" />
        ...

This is because you're using a route that contains an extension in it and by default Asp.Net will serve these files with a static file handler, bypassing the MVC pipeline and hence the Swashbuckle code. The above setting ensures the MVC pipeline is triggered for all requests. Of course, this may affect performance particularly if you are actually serving a lot of static content through your WebApi application. There's lots of blogs out there about that setting so a quick google should give you plenty of resources to learn more
