### ISSUE TITLE
Obsolete IncludeXmlComments and create equivalent called AddXmlCommentsOperationFilters

### ISSUE THREAD

**Issue by koolraap** [domaindrivendev/Swashbuckle#758]
IncludeXmlComments creates a couple of Operation Filters -- which means it has be called before any other filters that manipulate the documentation they generated. I wasted a fair amount of time working out why my MarkDown filter wasn't seeing any comments -- it was being called before IncludeXmlDocuments(), it wasn't obvious to me that that added items to the filter pipeline.

Renaming (obsolete for backcompat)  IncludeXmlComments, and any other startup methods that add filters, to indicate it adds filters would be beneficial to newbies.

**Comment by domaindrivendev** [comment]
I disagree - with any public interface I prefer to abstract the implementation details. What if decided to move the Xml Comments logic directly into the SwaggerGenerator as opposed to using filters (definitely something I've considered)? Now the public method name that all consumers are coupled to would make no sense anymore.

I think the root of your frustration is really because of a bug that meant it was possible for custom filters to execute before built-in filters. This is now fixed with https://github.com/domaindrivendev/Swashbuckle/commit/9b6ee1aa7e9143fb1d5e3731ae15b3e243cf7311 and will be released with the next milestone.

**Comment by koolraap** [comment]
Thanks, that's a good outcome. I didn't realise the behaviour I was seeing was not intentional.
