### ISSUE TITLE
Swashbuckle - Multiple API Version Methods to have the same path

### ISSUE THREAD

**Issue by lolekjohn** [domaindrivendev/Swashbuckle#775]
Hi,

We are designing an Web API project which have multiple versions of the same method. For supporting multiple versions, we have used multiple Controllers - CustomerVersion1Controller.cs and CustomerVersion2Controller.cs

These controllers have one method each - Get(). I want to have both these methods to have the same path i.e. api/consumer (but the response varies based on the version i.e. the controller method responses are different)

Based on the Accept Header version number being passed, the correct method will be called at run time. 

I can see that the calls are hitting correctly based on the version header passed along with the request. I had tested it in SOAP UI for seeing the response (the responses vary based on the version supplied.

I have integrated Swashbuckle to the project using the functionality - MultipleApiVersions

When i try to load the swagger UI, i can see that none of the methods gets listed for the Version 1 of the controller. These methods come up fine if i use different paths for the version1 and version2 of the controllers. 

Is there anyway i can use the same paths for the different versions?

**Comment by domaindrivendev** [comment]
Swashbuckle relies heavily on the built-in metadata layer - ApiExplorer. If you're using a custom controller selector to dispatch requests to the correct controller based on Accept Header version, then it's very likely  that your implementation is breaking ApiExplorer and hence Swashbuckle. 

It's worth noting that the WebApi team advise against customizing the controller selector for this reason because, among other issues, it breaks the descriptions generated by ApiExplorer. See the following for more info:

http://blogs.msdn.com/b/webdev/archive/2014/08/22/customizing-web-api-controller-selector.aspx

To get this working correctly with SB, you'll have to start by implementing your controller selection in a way that doesn't break ApiExplorer.
