### ISSUE TITLE
Provide API for generating Swagger.json without HTTP call

### ISSUE THREAD

**Issue by Danielku15** [domaindrivendev/Swashbuckle#783]
In our CI Server we want to generate always the current SDKs. For this we need to generate the Swagger specifications via command line after we compiled our Web API service (OWIN Windows Service). So basically:
1. Compile the Web API project
2. Invoke the compiled Exe with some CLI parameters that trigger the generation
3. Feed the output JSON into Swagger Codegen to update the SDK Sources
4. Compile the SDK 

For this it would be nice if Swashbuckle could provide some straight forward way to generate the Swagger JSON without the need to actually start the OWIN host. Currently everything seems to be wrapped into the SwaggerDocsHandler which holds the configuration.

**Comment by domaindrivendev** [comment]
This capability makes a ton of sense but is difficult because of the dependency on a fully loaded instance of `ApiExplorer`, which can't be easily instantiated outside of the full WebAPI stack. 

I think some form of in memory server makes the most sense. In the Core-specific project, [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore), I plan to implement this behind a simple CLI for generating the Swagger JSON. But, I hadn't planned on doing the same for this project.

However, you could easily implement this yourself with an `OWIN TestServer`. Here's a simple snippet that I threw together and appears to work well:

```csharp
using System.Web.Http;
using Microsoft.Owin.Testing;
using Owin;

namespace TestCli
{
    class Program
    {
        static void Main(string[] args)
        {
            var testServer = TestServer.Create(app =>
                {
                    var httpConfiguration = new HttpConfiguration();
                    YourApp.WebApiConfig.Register(httpConfiguration);
                    YourApp.SwaggerConfig.Register(httpConfiguration);

                    app.UseWebApi(httpConfiguration);
                });

            var swaggerResponse = testServer.HttpClient.GetAsync("swagger/docs/v1").Result;
            var swaggerJson = swaggerResponse.Content.ReadAsStringAsync().Result;
        }
    }
}
```
