### ISSUE TITLE
Show null in modelschema examples

### ISSUE THREAD

**Issue by VisualBean** [domaindrivendev/Swashbuckle#794]
I have a generic response model which looks like the following

```
{
"StatusCode": 200,
"Errors": null,
"Result": null
}

```

The problem is, when I override the default model, swashbuckle does not convey my empty errors or empty result 
![windows_10__display__2_](https://cloud.githubusercontent.com/assets/5294032/16035972/1dfc2a3c-321a-11e6-9c53-095f6de59eda.png)

**How do I get the UI to actually show that the Result parameter is still there, but would be null?**

My code looks like this

```
if (type == typeof (NotFoundException))
{
          schema.example = new ApiResponse<object>( HttpStatusCode.NotFound,null,
          new List<Error> { new Error { Reason = Reason.Not_Found.ToString(), Message = "Entity not found" }});

}
```

The signatur for the ApiResponse is httpstatuscode, result, List<errors>

**Comment by domaindrivendev** [comment]
This is because a swagger-specific JsonSerializer is used to serialize the SwaggerDocument. The settings include those necessary to output valid Swagger

**Comment by domaindrivendev** [comment]
For this SB project (i.e. specifically for WebAPI), you'll have to make do with the documentation as is. If you select the "Model Schema" tab instead of "Model" in the UI, I believe it should still list `Result` as a possible response field.

For [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore), the ASP.NET Core-specific project, examples will automatically be deserialized according to your application's serialization settings:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v1.0.0/src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerContractResolver.cs#L22
