### ISSUE TITLE
Json serializer settings are ignored in generated schema examples

### ISSUE THREAD

**Issue by mnikoo** [domaindrivendev/Swashbuckle#800]
In [SwaggerDocsHandler] (https://github.com/domaindrivendev/Swashbuckle/blob/953f9803bdf4a5051dd4ad90f8a6bc0ad8b6af3b/Swashbuckle.Core/Application/SwaggerDocsHandler.cs#L54) a new `JsonSerializerSettings` is instantiated: 

```csharp
SerializerSettings = new JsonSerializerSettings
{
    NullValueHandling = NullValueHandling.Ignore,
    Formatting = _config.GetFormatting(),
    Converters = new[] { new VendorExtensionsConverter() }
}
```

However in [HttpConfigurationExtensions](https://github.com/domaindrivendev/Swashbuckle/blob/f6a7d49f0a650386d9449fc269ad7858498a9b2d/Swashbuckle.Core/Application/HttpConfigurationExtensions.cs#L46) the formatter provided by http configuration is honored if one exists:
```csharp
internal static JsonSerializerSettings SerializerSettingsOrDefault(this HttpConfiguration httpConfig) 
{ 
    var formatter = httpConfig.Formatters.JsonFormatter; 
    if (formatter != null) 
        return formatter.SerializerSettings; 


    return new JsonSerializerSettings(); 
} 
```

Is this difference in behavior intentional? 

I think it is better to honor the formatter if one is configured. I am using `TypeNameHandling.Auto` serializer setting (I know it is not ideal but I am dealing with existing code and don't want to change it now) and this setting is ignored in schema examples generated by Swashbuckle. As I understand the first piece of code is used to generate the schema examples.

**Comment by domaindrivendev** [comment]
The difference is 100% intentional. To be compliant with the Swagger specification, the generated Swagger json must be serialized in a very specific way - ignore nulls, camelcasing etc. However, an application itself may use very different conventions for its JSON and thus the generated Swagger would be invalid if they shared the same serializer.

The issue with Schema examples is a known one (don't have # of the top of my head). The ideal solution is a Swagger specific serializer that delegates to the app-specific serializer for example fragments. This will be added in the next major version. In the meantime, you should just use anonymous with property names that reflect your JSON contract

**Comment by mnikoo** [comment]
That is a good point. The change I suggested can result in generation of invalid swagger document if one is not careful with the serializer settings.
