### ISSUE TITLE
Restricting access to swagger endpoint

### ISSUE THREAD

**Issue by saniokazzz** [domaindrivendev/Swashbuckle#804]
I use Swashbuckle, hosted in OWIN, and I need to protect both swagger UI and JSON with password. Any suggestions? https://github.com/domaindrivendev/Swashbuckle/issues/417 and https://github.com/domaindrivendev/Swashbuckle/issues/384 are duplicates, but both are closed without any resolution.

**Comment by figuerres** [comment]
we keep asking this and the author keeps closing the question...
I am looking at having to run a dummy site for internal users and deploying production without the swashbuckle package. I guess someone will have to get the code and hack in a fix for this and then ask the author to accept the fix so that we all get a real answer.  some day if I have time I will try to figure out how to do it but that's some day not next week.

**Comment by domaindrivendev** [comment]
Because people keep opening new issues in relation to this, as opposed to just re-opening the existing ones, there's now 8 or 9 of them and it's increasingly difficult to manage. Out of all these, I think there's two related but separate issues. So, I'm going to pick the canonical (original) issue for each case, re-open them and ask everyone to refer to them for future reference:

1. For restricting access to the Swagger endpoints (UI or JSON) - see #384 
2. For hiding certain operation descriptions based on the current identity - see #601

They were both previously closed because a valid approach was in fact suggested. To assist further, I've provided additional examples. Check out those issues for more details.

**Comment by lolekjohn** [comment]
I figured out the way to do this. Use the latest swashbuckle version and add the below div tag in the injected index.html

> <div id='auth_container'></div>

This will show an Authorize button in the swagger UI which can be used for authentication and once Authenticated, for all the requests to the API, the JWT token will be passed from the swagger UI

**Comment by betimd** [comment]
Is there any solution for this problem?

@lolekjohn the idea is not to pass login credentials in api calling, but to protect documentation ui at all.

**Comment by heldersepu** [comment]
@betimd No there is no solution yet. 
If you had to do it...  How will go about  protecting the documentation?

**Comment by AcidRaZor** [comment]
@heldersepu Just a normal Basic Auth request so that information about the API is restricted to only developers authorized to access the documentation. You guys must work on only open source projects that doesn't care if documentation and end-points get exposed to the public and get hammered with ddos attacks...

**Comment by heldersepu** [comment]
@AcidRaZor What's stopping you from sending a pull request?
You must be one of those that only takes from open source projects but never gives back.

**Comment by AcidRaZor** [comment]
@heldersepu Actually no. And if you knew how to implement Basic Auth, you would know it's not a Swashbuckle code issue that needs to be contributed to, but okay. I guess you're salty for some reason. I sympathize with you, this job can be quite demanding and soul-sucking if you let it.

**Comment by CreepyGnome** [comment]
Any way to solve this for ASP.NET Core Web API?  The solutions previously linked to won't work with Core.
