### ISSUE TITLE
Attribute routing - optional guid in url shows up as mandatory on Swagger ui

### ISSUE THREAD

**Issue by raghur** [domaindrivendev/Swashbuckle#809]
I have the following controller

```
[Route("{id:guid?}")]
        [HttpPost]
        [CustomAuthorize(roles:AzureAdGroups.IotAdmin)]
        public async Task<IHttpActionResult> Post([FromBody] CreateApplicationModel model, Guid? id = null)
        {
        ...
```

However, in Swagger UI, the id attribute is shown as `required`. What am I doing wrong?

Thanks!

**Comment by domaindrivendev** [comment]
Given that it uses path (sans query string) to uniquely identify operations, Swagger does not support the notion of optional "path" parameters. Have you considered putting the optional parameter in the query string?

Alternatively, you could split into two separate actions. It's worth noting that this wouldn't change your API contract. It just puts a different spin on it - instead of an operation with an optional path parameter, you have two seperate operations (or in REST terms "resources"). IMO this is a little more in line with REST and in particular the concept of Unique Resource Identifier (URI)

**Comment by raghur** [comment]
@domaindrivendev  thanks for helping with my noob question

I took the second approach and have split my action into two.
