### ISSUE TITLE
Wrong server name in curl request to NLB cluster

### ISSUE THREAD

**Issue by LbISS** [domaindrivendev/Swashbuckle#821]
I have set up load balancing between few servers. They getting requests through external name (outersite.ru on screenshot). I'm using next swashbuckle settings:

```
GlobalConfiguration.Configuration
	.EnableSwagger(c =>
		{
			c.RootUrl(req => GetServerUrl());
			...
		})
		
private static string GetServerUrl()
{
	return HttpUtility.HtmlEncode(HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority));
}
```

For the first glance it's working fine. But, if i'm trying to send any request - swagger is using inner server name in curl (serv11.domen.net:443), which is wrong. If i'm trying to use swagger outside of the domain - all request do not reach their destination.

![print](https://cloud.githubusercontent.com/assets/467427/16958288/8b45f21e-4de8-11e6-9983-df68b2bc8d5b.PNG)

**Comment by domaindrivendev** [comment]
This is a dup of #352. You're __RootUrl__ method is ultimately, via Request.Url, using the HOST header to determine your API host name. This won't work in a LB environment because it's value will be that of the inner host. Most LB's inject an additional header to indicate the original host name (e.g. "X-Forwarded-Host"). You'll need to identify which header has this data with your setup and update your GetServerUrl method.
