### ISSUE TITLE
Can't change DateTime format

### ISSUE THREAD

**Issue by PranKe01** [domaindrivendev/Swashbuckle#823]
Hi there,
I want to change the DateTime format my WebApi is sending.

In my WebApiConfig.cs I added the following line:
`GlobalConfiguration.Configuration.Formatters.JsonFormatter.SerializerSettings.DateFormatString = "yyyy-MM-dd";`

Now my WebApi is returning a DateTime field like 2016-07-22.
Now I need to change the generated docs, too. So I looked on the web and the documentation and found the MapType function.

In my SwaggerConfig.cs I added the following lines:
`c.MapType<DateTime>(() => new Schema { type = "string", format = "date" });
c.MapType<DateTime?>(() => new Schema { type = "string", format = "date" });`

After rebuilding the swashbuckle documentation still shows DateTimes like "2016-07-19T09:51:36.1568563+02:00" and not the required "2016-07-22".

I also tried the following to set a string date as default value. But it still shows the full date.
`c.MapType<DateTime>(() => new Schema { type = "string", @default = "2016-07-22" });`

What am I doing wrong, or am I missing something?

Thanks for your help!

**Comment by domaindrivendev** [comment]
Which version of SB are you using? I'm unable to repro your issue with the latest version (5.4.0).

It was most likely an issue with the swagger-ui because your approach is correct and I imagine the generated Swagger is correct too. I recently upgraded the version of swagger-ui in SB so perhaps this is where the fix was introduced.
