### ISSUE TITLE
How to change base url on core ?

### ISSUE THREAD

**Issue by bklooste** [domaindrivendev/Swashbuckle#831]
Using .net 4.6 and the new Asp Core 

Currently using 

```
        app.UseSwagger((httpRequest, swaggerDoc) =>
        {
            swaggerDoc.Host = httpRequest.Host.Value;
        });

        app.UseSwaggerUi();
```

but not sure how to do routes putting the url in  app.UseSwaggerUi(); did not work,

**Comment by bklooste** [comment]
putting in a url in app.UseSwaggerUi does not appear to work.

**Comment by domaindrivendev** [comment]
There is now a separate project specifically for ASP.NET Core and this allows custom routes to be specified for serving both the Swagger JSON endpoints and the SwaggerUI assets.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore

Check out the readme there and if you're still having issues please post an issue to that repo instead of this one (this is for the non Core version).
