### ISSUE TITLE
Unable see operations with same Route

### ISSUE THREAD

**Issue by anshumanshandilya** [domaindrivendev/Swashbuckle#855]
I am implementing versioning in my web api, so I want to keep same Routes for multiple operations in different controllers.

public class TestV1Controller : ApiController
    {
        [Route("Test/{id}")]
        public string GetData()
        {
            return "v1";
        }
    }

public class TestV2Controller : ApiController
    {
        [Route("Test/{id}")]
        public string GetData()
        {
            return "v2";
        }
    }

I implemented custom operation selector to be used in SwaggerConfig, so that I can choose which operation to display on help page. But SelectOperation method of my custom operation selector is only called once for the operation defined in the TestV1Controller. If I change the Route (which I don't want to) then SelectOperation method is executed twice for both operations and Swagger display both operations on help page. 

Is it that Swagger fetches all operations based on Route and returns the first operation if found duplicate on a specific Route?

**Comment by domaindrivendev** [comment]
I'm going to mark this as a dup because it's come up many times in many different issues. In summary, it's most likely due to a known issue with ApiExplorer and how it interacts with controller selectors - most custom implementations break ApiExplorer (WebAPI's built-in metadata layer). It's probably best described in one of the following #144, #755
