### ISSUE TITLE
Missing auth_container

### ISSUE THREAD

**Issue by MaximRouiller** [domaindrivendev/Swashbuckle#888]
Hi,

I've been trying to use the custom API Key by header shown in many examples. 

So my initial configuration had something like this:

```csharp
httpConfig
 .EnableSwagger(c => {
  c.ApiKey("ApiKey")
  .Name("ApiKey")
  .Description("Api Key used to invoke the API")
  .In("header");
 }).EnableSwaggerUi();
```

And the only thing that I saw was the "api_key" `input` in the header. This would only add to the URL no matter what I did. 

So compared the HTML of the original swagger-ui `index.html` and the one generated by Swashbuckle.

I've come to identify the problematic part.
```html
<form id='api_selector'>
	<div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text" /></div>
	<div class='input'><input placeholder="api_key" id="input_apiKey" name="apiKey" type="text" /></div>
	<div id='auth_container'></div> <!-- THIS IS MISSING -->
	<div class='input'><a id="explore" class="header__btn" href="#" data-sw-translate>Explore</a></div>
</form>
```

The original has an auth_container that will generate something like this:

![image](https://cloud.githubusercontent.com/assets/209384/19154557/fcea3d0a-8ba8-11e6-950f-624245971fc5.png)

Is this by design or is that a bug?

**Comment by domaindrivendev** [comment]
I left this out by design and stuck with the older version of index.html because the addition of the auth_container felt like it might be a breaking change for SB. It is included with the next major version release:

https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerUi/CustomAssets/index.html#L104

In lieu of this, take a look at #222 to get this working with the current version.
