### ISSUE TITLE
Upgrading from 5.4.0 -> 5.5.0 breaks index

### ISSUE THREAD

**Issue by pluppplupp** [domaindrivendev/Swashbuckle#912]
The stylesheetincludes is not longer parsed, looks like this:

![chrome_2016-10-28_09-03-50](https://cloud.githubusercontent.com/assets/1765023/19797845/df14b41c-9ced-11e6-9fbe-e07daa2af1af.png)

I'm running a modified version of index but I took the current version from 5.5 and with the same result..

Any ideas?

**Comment by Pjanssen** [comment]
I had the same issue, using a custom index.html. I found that it was caused by this change: https://github.com/domaindrivendev/Swashbuckle/commit/f71c4fce64bd160bb7853da4561ccaf162bab7a2

Changing this
`c.CustomAsset("index", thisAssembly, @"SwaggerUI.index.html");`
to
`c.CustomAsset("index", thisAssembly, @"SwaggerUI.index.html", isTemplate: true);`
fixed the issue.

**Comment by pluppplupp** [comment]
That did the trick! thanks!

**Comment by domaindrivendev** [comment]
Should be resolved in v5.5.2
