### ISSUE TITLE
Problem with ODataQueryOptions

### ISSUE THREAD

**Issue by kirimaru89** [domaindrivendev/Swashbuckle#96]
Hi, I'm new to SwashBuckle.

I've downloaded it from Nuget (Install-Package Swashbuckle -Version 4.0.0). It works very well with each method except this one

![image](https://cloud.githubusercontent.com/assets/391505/4522770/849ff7d2-4d2e-11e4-8961-09648c26c37b.png)

This is post method. However, its param will be passed in the URL (for example: http://localhost/api/products?$inlinecount=allpages&$skip=10). But Swashbuckle will display all properties of Product class, that's not what I want. I want it will be displayed as POST method, but the params will be added to the URL, like this:
![image](https://cloud.githubusercontent.com/assets/391505/4522827/60c0b670-4d2f-11e4-9db1-8c44e37d3bd5.png)

Is there any way to do this? Thank you :)

**Comment by domaindrivendev** [comment]
If you want to modify the generated Swagger for a given operation, you can implement a custom  IOperationFilter. For example:

    public void Apply(Operation operation, DataTypeRegistry dataTypeRegistry, ApiDescription apiDescription)
    {
        if (operation.Nickname == "SomeController_Get")
        {
            var optionsParam = operation.Parameters.Single(param => param.Name == "options");

            // Remove the body parameter
            operation.Parameters.Remove(optionsParam);

            // Add query param for each property in Product
            operation.Parameters.Add(new Parameter
            {
                Name = "property1",
                ParamType = "query",
                Type = "string"
            });

            // ...
        }
    }

This is the quick and dirty solution and could get you what you need. However, you could take it a step further and make the filter a bit smarter. Rather than hard-coding the params per operation you could inspect the existing metadata passed into the filter and modify all operations that meet the criteria. Between the operation, dataTypeRegistry (see it's GetModels method to find descriptions for any complex types in the controller) and apiDescription, you should have enough information to create a more general case filter.
