### ISSUE TITLE
Spec generation: Summary <returns> tag support 

### ISSUE THREAD

**Issue by bobahml** [domaindrivendev/Swashbuckle#97]
For example have the following ApiController method.

/// &lt;summary&gt;
/// Test summary
/// &lt;/summary&gt;
/// &lt;param name="id"&gt;Task id&lt;/param&gt;
/// &lt;response code="404"&gt;not found&lt;/response&gt;
/// &lt;returns&gt;Test result&lt;/returns&gt;
[HttpGet]
[ResponseType(typeof(TestResult))]
public async Task&lt;IHttpActionResult&gt; GetTest(long id)
{
      var result = await _testResultsRepository.GetByIdAsync(id);
      if (result == null)
          return NotFound();
      return Ok(result);
}

Is it possible to somehow implement support for tag &lt;returns&gt;?
&lt;returns&gt;Test result&lt;/returns&gt;

**Comment by MB34** [comment]
Well, to be honest, it doesn't look like your package supports ANY of the tags because this:
`/// <summary>
///     Gets Suggested Publications for the User
/// </summary>
/// <remarks>
///     This is a test call: /mp/SuggestedPublications/c35f570/999999/CC,SR,RM,SRM
/// </remarks>
/// <param name="LogonTicket" required="true">The LogonTicket (required) needed to access this function.</param>
/// <param name="PID">The UserID of the user needing the suggested publications for.</param>
/// <param name="designations">Comma Separated list of Designations held by User.</param>
/// <returns>JSON list of Suggested Courses for the passed User</returns>`

Shows this:
![swashbuckle2](https://cloud.githubusercontent.com/assets/377196/20119261/71444ff4-a5cd-11e6-839c-e6ab0d333b95.png)

I don't see a summary, a remark or parameters comments, much less the return description.
